### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#106]
### Upcoming Events Card Responsive issue for Mobile View

- [x]  Make a different layout for UpcomingEvent below 1024px 
- [x]  adjust speaker name size for mobile screen
- [x]  Right side of the mobile view padding needs to be adjusted

- [x]  All blue button checks only blue-btn class should be there

### [event_id] page

- [x]  Instructor/speaker grid should be responsive properly

### Footer

- [x] Make properly Responsive

### Events Page

- [x] for screen between 600-1024px padding in X needed to be reduced

**Comment by Kingshuk3006** [comment]
Event Page can't load due to lenght 0.add some data.

**Comment by Rajdip019** [comment]
There is data! ask @Debajyoti14 , @Kingshuk3006

**Comment by Debajyoti14** [comment]
There is data.
I can see an event in https://clueless-dev.vercel.app/events
@Kingshuk3006

**Comment by Rajdip019** [comment]
Closing this issue as it is solved. @Kingshuk3006
