### ISSUE TITLE
Make Event Page as in the Figma Design

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/clueless-official-website#110]
There is more spacing and the UI looks much more neat and clean in design. @Kingshuk3006

**Comment by Kingshuk3006** [comment]
Done

**Comment by Rajdip019** [comment]
3rd point is already done @Kingshuk3006. You can work on first two points

**Comment by Rajdip019** [comment]
Can you look into this one @Debajyoti14 . Just need some vertical space. On this page and else is good to go I guess. And the 2nd point will also be done when we will apply the view ticket section.

**Comment by Rajdip019** [comment]
This event is solved nice work @Kingshuk3006
