### ISSUE TITLE
Add Delete Modal 

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/clueless-official-website#111]
Before deleting a project from the Admin panel of a user. There should be a confirmation pop-up if he wants to delete it or not!

You can see pop-ups build by @Debajyoti14 in the components section. (Use the same code pass the id there and delete it.)

@Kingshuk3006

**Comment by Rajdip019** [comment]
Use a modal instead of a Dialogue box to achieve paddings and better styling! @Kingshuk3006 

![Screenshot 2022-08-09 025554](https://user-images.githubusercontent.com/91758830/183517616-b703631a-3443-440f-84a8-1316d4787fbe.jpg)

**Comment by Kingshuk3006** [comment]
![modal](https://user-images.githubusercontent.com/93638401/183574336-f81431ae-484a-439d-8265-85e30567a4cd.png)
the dialog seem to have fixed padding in my end.

**Comment by Rajdip019** [comment]
You have padding for MUI paper element in global CSS, you have to remove that because it's only for this modal not global. It breaks all the menu and other modals. 

Take the latest pull from dev.

@Kingshuk3006

**Comment by Rajdip019** [comment]
This is finished so closing this Issue.

**Comment by Rajdip019** [comment]
This is finished so closing this Issue. @Kingshuk3006
