### ISSUE TITLE
Implement dark mode

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/clueless-official-website#116]
The whole UI is build with Tailwind CSS and Material UI. All you need to do is write the main logic of dark mode in a .ts file and implement a button that changes the whole website mode to dark mode.

There will be three type of modes.
- Dark mode
- Light mode
- System Default

The actual conversion from light to dark mode will be done separately. You just need to make the button that changes the mode with a small example.

You can checkout this documents for help : [Tailwind CSS Dark mode](https://tailwindcss.com/docs/dark-mode)

**Comment by AKACHI-4** [comment]
Hey @Rajdip019  Can I work on this issue Plz assign it to me so I can generate PR as soon as possible

**Comment by Rajdip019** [comment]
Sure. you are assigned.

**Comment by adi-uchiha** [comment]
I have made dark mode website with tailwind css. Can I start working on this ?

**Comment by Debajyoti14** [comment]
@AKACHI-4 Is it completed?

**Comment by AKACHI-4** [comment]
I am working on it and will create PR soon.

**Comment by Debajyoti14** [comment]
@AKACHI-4 Update on your progress?

**Comment by YashJain2409** [comment]
Can I work on this?

**Comment by Debajyoti14** [comment]
@AKACHI-4 unassigning you.
@YashJain2409 assigned you.

**Comment by YashJain2409** [comment]
hey, you can unassign me , actually i do not know that much about tailwind css

**Comment by RajKanani1206** [comment]
If this is still available, I would like to work on it and can u tell me more about the dark mode feature, I'm a bit confused between the instructions above.

**Comment by RajKanani1206** [comment]
If this is still available, can u tell me more about the feature. I'm interested in working at it.

**Comment by soustab10** [comment]
I'm interested in working on this.

**Comment by Debajyoti14** [comment]
@RajKanani1206 assigned you

**Comment by devjain2309** [comment]
@Rajdip019 Can I Add dark mode on the main page?

**Comment by Debajyoti14** [comment]
@RajKanani1206 Yes. Just make sure while changing it to Dark Mode, The text colours also changes to appropriate colour so that readability remains intact

**Comment by Debajyoti14** [comment]
@RajKanani1206 What's the update?

**Comment by RajKanani1206** [comment]
@Debajyoti14 Would provide update with short outcome soon.

**Comment by RajKanani1206** [comment]
@Debajyoti14 

https://user-images.githubusercontent.com/104709529/196033175-eb99ad4d-6238-4542-b6e5-2ddee5d0d149.mp4

Note: 
-- I have kept sure about text color for home page only, every other page needs to be addressed for dark mode.
-- I have used next-themes(npm package), hope there is no issue in that.

What needs to be done: 
-- Reposition mode changing icon properly.
-- Github logo svg in Dive into the world of Development section needs to be updated for dark mode.
-- Second svg in Our Community Partners section needs to be updated for dark mode.
-- Changing mode selection dropdown background color for dark mode.

**Comment by Debajyoti14** [comment]
@RajKanani1206 Okay There is too much changes needed to be done in order to implement dark mode.

Let me discuss with the other members and merge it if approved.

Hold it for a bit.

**Comment by RajKanani1206** [comment]
@Debajyoti14 Yes sure, I guess doing all changes in one PR would not be the best solution.

**Comment by Debajyoti14** [comment]
@RajKanani1206 Make a PR, We will make the changes for the Dark mode

**Comment by RajKanani1206** [comment]
@Debajyoti14 Done.
