### ISSUE TITLE
Need a small documentation for the Official Website.

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/clueless-official-website#123]
- What is Clueless? With some pictures.
- What is our aim?
- People working on it.
- Link to projects we are building under ClueLess
- A link to how to set up this project in the local System. (If Someone wants to contribute) . That readme will be built by @Debajyoti14 probably.

**Comment by nikhil25803** [comment]
On it :)

**Comment by Rajdip019** [comment]
Make sure to make the PR in the Dev branch, not in the main branch. @nikhil25803

**Comment by nikhil25803** [comment]
Okay

**Comment by Rajdip019** [comment]
Can we finish this by today? The how to setup this is local system, ReadMe is already build by @Debajyoti14 . So you just need to link that one here as well. @nikhil25803

**Comment by nikhil25803** [comment]
I'll do it by tonight. Will it work?

**Comment by Rajdip019** [comment]
Sure it will work. @nikhil25803
