### ISSUE TITLE
Local system environment setup

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/clueless-official-website#124]
Write a proper note on how one can set up this project in his local machine.

We don't need to give the env there but we can ask them to drop a mail to the Official ClueLess email for the env and we will send the env after validation.

See the documentation of Booklee to know how to document the env part.

**Comment by Debajyoti14** [comment]
local_env_setup_guide.md has been configured

**Comment by Rajdip019** [comment]
Done for now! @Debajyoti14
