### ISSUE TITLE
Build edit event page in the admin section 

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/clueless-official-website#128]
This page edits the data of the existing event.

This is a cool one to do because it has some cool front-end as well as some backend and logical things going on! 

Ask @Debajyoti14 if you need help in this one. 

And you can take a reference of the edit profile page to get how these types of things are done. We need to get this done before Tuesday!

@Kingshuk3006

**Comment by Kingshuk3006** [comment]
Routing left to do properly

**Comment by Rajdip019** [comment]
I guess this one is done properly so closing this issue as well. @Kingshuk3006
