### ISSUE TITLE
Event card UI Fixes

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/clueless-official-website#131]
Need some Spacing here. at different screen sizes.

![Screenshot 2022-08-07 173057](https://user-images.githubusercontent.com/91758830/183289563-6dc67ad2-74da-4102-af73-8d402aacee79.jpg)

And also here.
![Screenshot 2022-08-07 173139](https://user-images.githubusercontent.com/91758830/183289571-262e4c52-2277-4af2-ad27-aaa43eb3126d.jpg)

We need to get this event card perfect by today!

**Comment by erum-hassan** [comment]
**Can i take **

**Comment by Rajdip019** [comment]
It's already assigned to @Kingshuk3006, if he doesn't do it you can take it. @erum-hassan

**Comment by Rajdip019** [comment]
Closing this issue as it is fixed now! @Kingshuk3006
