### ISSUE TITLE
Event Page Header

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/clueless-official-website#133]
The Header should be Clueless | Events for the all events page and for a particular Event page, this should be [The event name]. And when shared that page should also show the Logo of the event.\

Here is a reference for what you need to change! 
![Screenshot 2022-08-08 155647](https://user-images.githubusercontent.com/91758830/183397826-2ef9a4fd-ef4f-42b0-87e7-644b1246f13e.jpg)

**Comment by Kingshuk3006** [comment]
for share link, need some reference.

**Comment by Rajdip019** [comment]
Quick fix for the event page it's right now " Clueless | Session Zero ". Instead we just want " Session Zero ". @Kingshuk3006

**Comment by Rajdip019** [comment]
Fixed this one myself no problem @Kingshuk3006 . So closing the issue.
