### ISSUE TITLE
Event Null state

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#134]
When no event data is there, there should be an empty state stating "There are no Events currently" alongside an SVG.

**Comment by Rajdip019** [comment]
Can you make a quick Figma design for reference with 3d SVG, we are using @Debajyoti14

**Comment by Debajyoti14** [comment]
Design has been done

**Comment by Rajdip019** [comment]
Use an image without a watermark. And also add more events on the way in the text part. @Debajyoti14

**Comment by Debajyoti14** [comment]
Event Null state feature is added by me
Go and check
if everything's good, close this issue @Rajdip019

**Comment by Rajdip019** [comment]
This one right? #138 @Debajyoti14

**Comment by Rajdip019** [comment]
Closing this as its working fine.
