### ISSUE TITLE
Event Mode Field in Event Model

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#149]
There should be a field named event mode with offline/online options

**Comment by Debajyoti14** [comment]
Yes @Rajdip019

**Comment by Rajdip019** [comment]
I am doing the multiple auth and trying to make a callback function for to redirect user to the page where they were before and not in the Homepage. I will look into this after that if you work on this before that then tell me @Debajyoti14

**Comment by Debajyoti14** [comment]
Added Event Mode Field
