### ISSUE TITLE
Apply check in Contact form

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/clueless-official-website#164]
In the contact us form there is no check. Users can only contact when they are signed In and fill all the fields in the form.

Till then the button should be disabled. 

I guess you can do it @Kingshuk3006

**Comment by Akidane47** [comment]
If this is still available and open-source I'd also like to be assigned.

**Comment by Rajdip019** [comment]
Sure go ahead. You are assigned. @Akidane47

**Comment by Akidane47** [comment]
What are the setup instructions? I clicked on the link in the README file but it caused a 404 error

**Comment by Rajdip019** [comment]
Try now I have changed it now. And also you don't need to set up an env for this. So you can skip that part too. @Akidane47

**Comment by Rajdip019** [comment]
Hey are you still working on this @Akidane47 ?

**Comment by Akidane47** [comment]
Yes sorry was having some trouble with setting up credentials but it's
fixed now, will be sending my version later today

**Comment by Rajdip019** [comment]
No worries! Take your time. @Akidane47 .

**Comment by Rajdip019** [comment]
Is this completed? @Akidane47

**Comment by ridhig16** [comment]
If this is still available and open-source I'd also like to be assigned and can u tell me more about this issue

**Comment by Rajdip019** [comment]
Yes sure I will assign you. 

what you need to do is just make the 'submit' button disable until all the fields are filled. @ridhig16

**Comment by akebu6** [comment]
This issue seems to not be assigned to anyone, can I have it assigned to me if that is the case?

**Comment by Rajdip019** [comment]
Yes sure. Go ahead! @akebu6

**Comment by akebu6** [comment]
Hey @Rajdip019, I am having issues with VSCode enabling TypeScript so it will take a while for me to work on this issue. Latest I should have it done this weekend after my College project proposal. Hope that is still okay

**Comment by Rajdip019** [comment]
Yes it's fine. Take your time @Akidane47

**Comment by jyotika6221** [comment]
I m a beginner, can u please describe the isssue in detaila nd assign it to me?

**Comment by akebu6** [comment]
Hey @jyotika6221 I'm actually working on this so, can you kindly find another open issue go work on

**Comment by RajKanani1206** [comment]
Hey @Rajdip019, I think users can also contact when they are not signed In (Ref: https://ineuron.ai/contact-us), also disabling submit button would not be the best option. I guess form should be validated. I can get it done if assigned to me.

**Comment by akebu6** [comment]
@Rajdip019 I think you can also assign it to @RajKanani1206 to make the form validation because I've also noticed that the firm inputs aren't validated.

He can work on the form validation part and I'll finish up the disable button until all fields and validation are done.

How does that sound @RajKanani1206 and @Rajdip019 ??

**Comment by Rajdip019** [comment]
Okay work on it. @RajKanani1206

**Comment by RajKanani1206** [comment]
Done. I have created PR.
