### ISSUE TITLE
Make the admin Projects card UI Component

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/clueless-official-website#168]
Just need to revamp the UI of the Project Admin card. 

Need to implement this design.

<img width="578" alt="Screenshot 2022-09-30 at 1 07 22 PM" src="https://user-images.githubusercontent.com/91758830/193217613-e055975a-97dc-4418-a955-3b7bb1bf5944.png">

Here is a link to the Figma File.
[Figma File](https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=204%3A5014)

**Comment by boredcity** [comment]
isn't it just a Profile Project card from [this](https://github.com/Clueless-Community/clueless-official-website/issues/169) issue?

if there are some underlying differences, I'd be happy to work on this.

**Comment by Rajdip019** [comment]
This is the admin card and that one is the normal card for visitor view. This card is a bit difficult as there is an edit modal attached to it.

@boredcity .

If you want to work on this please confirm. I will assign you!

**Comment by boredcity** [comment]
Oh, now I see, thank you!

Would it still make sense to wait until the Profile Project Card is ready to reuse the code?

I can work on the modal for now and then merge it with the card component (and add the edit button as well) if this makes sense to you. 👍

**Comment by Rajdip019** [comment]
The modal is already built. I am assigning you the issue for now. You can wait for the profile card to be finished and the re-use the code. @boredcity

**Comment by Rajdip019** [comment]
Hey @boredcity the projects card UI is built, now you can start working on this you can find the new projects card UI in the `dev` branch only.

**Comment by boredcity** [comment]
@Rajdip019 
I finally started working on the new admin Projects card (sorry for the delay), but I have a few questions while I'm waiting for the credentials:

1) Should "Deployed URL" be a required field in the modal? Right now it's not, but the form won't save unless you provide it (and also does not give any indication that this is required 😿 )
![image](https://user-images.githubusercontent.com/3993495/193774571-b8511e1e-366e-4389-b18c-c5a82e90769a.png)

2) Should there be a smaller limit on how many characters can be in a project's title and description? Alternatively, should I use line-clamp or something like that? Right now it can get quite long and ruin the intended design.
![image](https://user-images.githubusercontent.com/3993495/193771639-944288d0-85bf-4bcf-aa7f-c28deca08dea.png)

**Comment by boredcity** [comment]
Still no letter with credentials, by the way... 😕
Is it possible to check whether you have received my email with the credentials request as per instruction in `CONTRIBUTING.md`? 🕵️

**Comment by Rajdip019** [comment]
Sent the credentials check once @boredcity

**Comment by Rajdip019** [comment]
And for your question
1. The Deployed URL should not be a required field.
2. We can have a 300 letter limit I guess there.

**Comment by boredcity** [comment]
One more question: should there be a delete project button in the new design?

**Comment by Rajdip019** [comment]
Yes there should be. Just saw it's not there in the Figma design.
