### ISSUE TITLE
Make Profile Project Card Component 

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/clueless-official-website#169]
Just need to revamp the UI of the Project card. 

Need to implement this design.

<img width="563" alt="Screenshot 2022-09-30 at 1 07 41 PM" src="https://user-images.githubusercontent.com/91758830/193218181-afa57dab-2c96-430d-acae-b94c03bc140e.png">

Here is a link to the Figma File.
[Figma File](https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=204%3A5014)

**Comment by Sayak-singha** [comment]
Should there be only 3 cards at a time??

**Comment by Rajdip019** [comment]
No it will be decided by the amount of projects the user has added, which directly comes from Firebase Firestore.

It will be component. 

@Sayak-singha

**Comment by ken1000minus7** [comment]
Hey @Rajdip019 I would like to work on this issue 😇

**Comment by Rajdip019** [comment]
Sure assigning you this issue. @ken1000minus7

**Comment by Rajdip019** [comment]
Closing this issue as it is done. @ken1000minus7
