### ISSUE TITLE
Change the current Add Project section according to the new UI

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/clueless-official-website#170]
Just need to revamp the UI of the Add project. 

Need to implement this design.

<img width="186" alt="Screenshot 2022-09-30 at 1 07 32 PM" src="https://user-images.githubusercontent.com/91758830/193218578-58bd2e01-34af-4e52-b606-a5d918c7a3b8.png">

Here is a link to the Figma File.
[Figma File](https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=204%3A5014)

**Comment by iks1** [comment]
can you assign this to me ?

**Comment by Rajdip019** [comment]
Yes, go ahead!

**Comment by Debajyoti14** [comment]
@iks1 What's the update?

**Comment by its-ayush-07** [comment]
@Debajyoti14 I'd like to work on this issue

**Comment by Debajyoti14** [comment]
Will assign within today if @iks1 doesn't respond.

**Comment by rahulkarda** [comment]
@Debajyoti14 Assign it to me, if they don't respond.

**Comment by Debajyoti14** [comment]
@its-ayush-07 assigned you.
