### ISSUE TITLE
Implement the new Profile Design 

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/clueless-official-website#171]
Just need to revamp the UI of the Profile Section. 

Need to implement this design.

<img width="437" alt="Screenshot 2022-09-30 at 1 16 05 PM" src="https://user-images.githubusercontent.com/91758830/193219011-e8da2f84-5950-4b86-abdb-c8d9065e566f.png">

Here is a link to the Figma File.
[Figma File](https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=204%3A5014)

**Note** : This will be done after the Project Admin card and Project Card UI is done.

**Comment by arun-kushwaha04** [comment]
Hey @Rajdip019 can I work on this issue ?

**Comment by Rajdip019** [comment]
Yes once the cards are finished we can start working on this.

**Comment by Yash-Parwani** [comment]
Hey, @Rajdip019  can I also work on this issue?

**Comment by Rajdip019** [comment]
As this is on first come first serve basis @arun-kushwaha04 will get to work on this issue first. But we will be adding more issues by today night. 

Also if you find any bug or want to enhance something on the website you can always open an issue for that. @Yash-Parwani

**Comment by arun-kushwaha04** [comment]
@Rajdip019 thanks for assign this to me. I will start working on this on.

**Comment by AbirSantra** [comment]
@Rajdip019 Let me know if I can work on this issue after them.

**Comment by Rajdip019** [comment]
Hey, @arun-kushwaha04 do you want to work on this now?

**Comment by arun-kushwaha04** [comment]
Yes

**Comment by Rajdip019** [comment]
Go ahead now you can start working on this. @arun-kushwaha04

**Comment by Debajyoti14** [comment]
@arun-kushwaha04 Any Updates?

**Comment by arun-kushwaha04** [comment]
@Debajyoti14, Yes I have started working on the new profile section. Please Exculse me i got busy with some family work.

**Comment by arun-kushwaha04** [comment]
@Rajdip019 where can I find google client id and secret id for local setup ?

**Comment by arun-kushwaha04** [comment]
@Rajdip019 @Debajyoti14 I didn't received api credentials for local setup.

**Comment by Debajyoti14** [comment]
@arun-kushwaha04 mail us once again at official.cluelesscommunity@gmail.com with the PR link and your GitHub ID

**Comment by arun-kushwaha04** [comment]
@Debajyoti14 sent.

**Comment by Harsh0326** [comment]
Hey @Rajdip019 can I work on this issue ?

**Comment by Ayush2020012016** [comment]
Hey brother as I dont have any work to do for right now can i do this work. thank you

**Comment by rahulkarda** [comment]
@arun-kushwaha04 are you still working on the issue?
