### ISSUE TITLE
Enhancement: Write an issue template

### ISSUE THREAD

**Issue by VividhPandey003** [Clueless-Community/clueless-official-website#181]
At present, there is no issue template in the clueless-official-website as well as other repositories of Clueless-Community. 
In order for beginners in the field of OpenSource to enjoy working together, we need an Issue template.
Adding an issue template would promote Contribution as well as will make the work easy for maintainers to read the issues.

If this issue sounds valid, I would love to work on this issue😊.

**Comment by Rajdip019** [comment]
Hey, @VividhPandey003 . It's a great idea. Surely you can work on this, Can you give a brief overview of the issue template you are thinking to add?

**Comment by VividhPandey003** [comment]
Hey @Rajdip019, I was thinking to divide it into different readmes' like bug report, feature request etc. What are your views regarding this

**Comment by Rajdip019** [comment]
Yes we can do that. Let's do this I am assigning you the issue.

**Comment by VividhPandey003** [comment]
> Yes we can do that. Let's do this I am assigning you the issue.

Thanks a lot. I'll submit a Pull Request soon

**Comment by VividhPandey003** [comment]
Hey @Rajdip019 , I've made a Pull request. Please review it once. Also another doubt, should I add pull request template as well as another commit in this pull request.

**Comment by Rajdip019** [comment]
Sure @VividhPandey003

**Comment by Rajdip019** [comment]
I guess this is done. So closing this issue.
