### ISSUE TITLE
Make changes in Navbar for better user Interface🎏

### ISSUE THREAD

**Issue by nihal-soni** [Clueless-Community/clueless-official-website#182]
🐞 Problem
I saw Your Website or I thought that  we can improve navbar better and toggle button for day and night theme.🎗

🎯 Goal
And this change will be very helpful for you , by changing this thing, your website will start looking user friendly, whoever will visit your website , will going to feel that what a cool website.

💡 Possible solutions
we can change the navbar styling by adding day and night theme.👌
We can change the background color in linear gradient color.
we can make changes in fonts and the styling of text.

I will be really happy if you can make this changes in the website.

Thank you.😊

**Comment by Debajyoti14** [comment]
Can you share with us the design of the navbar by creating it in Figma?
Then we can proceed further @nihal-soni

**Comment by nihal-soni** [comment]
yes ofcourse its my pleasure

**Comment by nihal-soni** [comment]
and i would like to contribute to the project @Debajyoti14

**Comment by Debajyoti14** [comment]
Fine @nihal-soni.
I'm assigning this issue to you.
Let's first make the layout in Figma & then implement this.👍️

**Comment by nihal-soni** [comment]
Thank-you so much 

I will Do my Best😊

**Comment by nihal-soni** [comment]
How much Time I have to this Bhaiya....

**Comment by Debajyoti14** [comment]
There's no such limit.
Just make sure you complete this within appropriate time.

**Comment by nihal-soni** [comment]
ok

**Comment by nihal-soni** [comment]
@Debajyoti14  I have started working on navbar  designing

**Comment by nihal-soni** [comment]
@Debajyoti14     Bhaiya design is ready
[Clueless navbar.pdf](https://github.com/Clueless-Community/clueless-official-website/files/9694838/Clueless.navbar.pdf)

**Comment by Debajyoti14** [comment]
@nihal-soni actually we think that currently Navbar is good at it's place.
btw thanks for your effort.
Really appreciate it.
Keep looking for other issues and contribute.
As of now closing it.

**Comment by nihal-soni** [comment]
No problem ,
Thankyou for appreciation.....
