### ISSUE TITLE
Icons overlapping in What is Clueless section 

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#184]
### Just separate the icons so that it does look good for all screen sizes 👍️

![Screenshot from 2022-10-02 16-06-24](https://user-images.githubusercontent.com/91759192/193449786-d67f19df-13e3-4fa5-a196-91286ea8c2a1.png)

**Comment by rahul-n18** [comment]
Could you elaborate a bit

**Comment by Debajyoti14** [comment]
As you can see in the picture 
The top two icons are getting overlapped with each other for small-screen laptops.
What you have to do is just space out these two icons for that specific screen so that the UI looks better

**Comment by rahul-n18** [comment]
Assign me ill do it

**Comment by Debajyoti14** [comment]
Assigned it to you👍

**Comment by Debajyoti14** [comment]
@rahul-n18 What's the progress?

**Comment by rahul-n18** [comment]
@Debajyoti14  I have sent you a mail long back Please refer it once

**Comment by Debajyoti14** [comment]
@rahul-n18 I haven't found any mail. Have you made the PR? if yes share the link to the PR.

**Comment by jyotika6221** [comment]
Is the issue resolved or can i fix it?

**Comment by rahul-n18** [comment]
@jyotika6221 you can do this.

Thank you

**Comment by Debajyoti14** [comment]
@jyotika6221 assigning it to you.

**Comment by Debajyoti14** [comment]
@jyotika6221 This issue was fixed previously.
Pick another issue.
So closing it for now.
