### ISSUE TITLE
All Section width in hacktoberfest page needed to be the same 

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#185]
### play with the width or padding to fix this issue 👍️

![Screenshot from 2022-10-02 16-18-58](https://user-images.githubusercontent.com/91759192/193450292-0d203174-d0e5-4b0b-a7d2-f80c7fb417df.png)

**Comment by Skysparko** [comment]
can i work on it?

**Comment by Debajyoti14** [comment]
Yup👍
Assigning it to you.

**Comment by Dhanush-2605** [comment]
hi, @Debajyoti14 can I work on this?

**Comment by Ahnaf-codes** [comment]
@Debajyoti14 I'd like to work on this

**Comment by AbirSantra** [comment]
@Debajyoti14 Can I work on this?

**Comment by Debajyoti14** [comment]
@Dhanush-2605 assigning it to you👍️

**Comment by Dhanush-2605** [comment]
@Debajyoti14  what exactly should i do 
![image](https://user-images.githubusercontent.com/90703523/193744678-f83c6977-99ce-49c7-b9aa-fbf9dd82f702.png)
because width of all div are already same right?
