### ISSUE TITLE
Techstack icons should be center alligned

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#186]
### From 768px to 1024px, The Techstack icons needs to be center alligned 

![Screenshot from 2022-10-02 16-29-29](https://user-images.githubusercontent.com/91759192/193450640-6d440854-ab18-46bf-8e7f-83e66478ba4a.png)

**Comment by heisdinesh** [comment]
can i work on this issue @Debajyoti14

**Comment by Debajyoti14** [comment]
Sure go for it 👍
Assigning it to you.

**Comment by PrinceX04** [comment]
Can i work on this issue

**Comment by Debajyoti14** [comment]
This issue is already resolved.
So closing this.
