### ISSUE TITLE
Change the SVG as it is overlapping with the background

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#187]
### Find a better SVG that matches the theme of the website and replace it with the previous one so that it goes well with the dark background.

![image](https://user-images.githubusercontent.com/91759192/193450858-5172fa9c-2b70-420b-9b8f-a50978c36c4d.png)

**Comment by PrinceX04** [comment]
Can i work on this issue?

**Comment by Debajyoti14** [comment]
Okay!
Assigning it to you 👍️

**Comment by PrinceX04** [comment]
@Debajyoti14 Can you help me with where i have to save this file and make a PR for the same.

**Comment by DireWolf707** [comment]
Pls assign
So I can start working on it !
Thx

**Comment by PrinceX04** [comment]
@Rajdip019  As requested I had made another pull request to the dev branch

**Comment by Rajdip019** [comment]
Okay I will check @PrinceX04
