### ISSUE TITLE
Fix spacing issues in Hacktoberfest Page

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#188]
### 1. Top & Bottom spacing of Guidelines needed to fix appropriately.
![image](https://user-images.githubusercontent.com/91759192/193451085-8c0bf4b0-3a77-487d-b07b-55712de75e06.png)

### 2. The bottom padding needs to be fixed.
![image](https://user-images.githubusercontent.com/91759192/193451109-9411fe5d-e358-4036-9f9a-3e6bd46b96f6.png)

### 3. The space between Read More button & SVG needs to be increased.
![image](https://user-images.githubusercontent.com/91759192/193451144-68590eaf-23bd-48b6-8869-ec5378759341.png)

**Comment by anirudh-bukka** [comment]
I want to work on this.

**Comment by Debajyoti14** [comment]
Yup👍️
Assigning it to you.

**Comment by Anshumansengar** [comment]
Hey, Can you assign me if it is not yet fixed? I would like to work on it.

**Comment by Debajyoti14** [comment]
@Anshumansengar don't worry.

@anirudh-bukka is assigned now. If the issue remains after the pr of Anirudh. We will assign it to you.

Till then look into other repos and contribute 👍

**Comment by anirudh-bukka** [comment]
Hey @Debajyoti14 , can you pls link the page that needs to be fixed? I'm unable to find the exact page.

**Comment by Debajyoti14** [comment]
https://www.clueless.tech/hacktoberfest
This is the link

**Comment by anirudh-bukka** [comment]
Hey @Debajyoti14 can you assign it to anyone else? 

Ambushed with assignments and mid term.

**Comment by Garvit1809** [comment]
hey, can I take the issue??

**Comment by AbirSantra** [comment]
I would like to work on this issue. Let me know if you want to assign me to this.

**Comment by Debajyoti14** [comment]
Ok,
@Garvit1809 assigning it to you.
@AbirSantra will assign it to you after @Garvit1809

**Comment by Garvit1809** [comment]
1) Guidelines issue:-
![Contri2](https://user-images.githubusercontent.com/89806031/193777282-363d5280-37ca-409c-96f5-84a8e695192b.png)
2) Margin Bottom issue:-
![Contri4](https://user-images.githubusercontent.com/89806031/193776959-ab351b96-d68f-4d8c-adc7-c769e4993dfe.png)
3) Space between Read more and SVG
![Contri3](https://user-images.githubusercontent.com/89806031/193777435-5a1433bb-afd3-41dd-ac4c-09a5cae345cd.png)

@Debajyoti14 can u see if this is good or not

**Comment by Debajyoti14** [comment]
increase bottom padding a little at 2

**Comment by Garvit1809** [comment]
Now looks good ?? Added a bit of margin in image as well as the heading
![Contri5](https://user-images.githubusercontent.com/89806031/193825141-a80c6bae-c3f3-49f6-a8ab-4970991c0e32.png)
