### ISSUE TITLE
Adding a good looking scrollbar matching with the theme of the website

### ISSUE THREAD

**Issue by jaydeepdey03** [Clueless-Community/clueless-official-website#191]
I want to add a good looking scrollbar in the website, which would match with the theme of the website, incorporating linear gradient color pattern in the scrollbar.

**Comment by SahilSingh177** [comment]
Can I work on this issue?

**Comment by Debajyoti14** [comment]
We have already changed that scrollbar color to blue previously but it wasn't looking good.
So, closing this issue.
