### ISSUE TITLE
Improve button designs in the hero section

### ISSUE THREAD

**Issue by AbirSantra** [Clueless-Community/clueless-official-website#194]
Hey, I was visiting the website and one of the first things I noticed is that the 'Join Discord' button has no border radius as opposed to every other button on the website. So I would like to add some radius to the borders. 

Also, the "Explore Events" button has no icon. So I would like to add an icon to maintain uniformity.

The screenshot is attached below.

I would like to work on these issues under Hacktoberfest 2022. Can I start working on this?

![image](https://user-images.githubusercontent.com/78201921/193585816-e8d66846-df1d-4696-add0-78560dbc24c0.png)

**Comment by Debajyoti14** [comment]
We appreciate your suggestion!
As of now, We decided to not work on this as we think that the join Discord button is good without border-radius and also the blue button is also giving justice to the Design system.
Feel free to raise issues like this.
As of now closing this issue 😀
