### ISSUE TITLE
The project cards are overlapping 

### ISSUE THREAD

**Issue by codeswithroh** [Clueless-Community/clueless-official-website#195]
Issue: All the cards under the projects sections are overlapping over one another
Screenshot:
![check](https://user-images.githubusercontent.com/77570394/193667137-3672c788-7ed6-4511-9184-397866779980.png)

Recommended Solution:
Reduce the width of the cards at full screen to stop the overlapping

**Comment by codeswithroh** [comment]
@Debajyoti14 @Rajdip019 Could you assign this to me

**Comment by Debajyoti14** [comment]
Sure, Assigned it to you 👍
