### ISSUE TITLE
Add link to the Readmore button in Guidelines Button

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#196]
#### Add (https://github.com/Clueless-Community/clueless-official-website/blob/main/CODE_OF_CONDUCT.md) href to the link tag in the Read More button also make sure that it opens in new Tab.

![image](https://user-images.githubusercontent.com/91759192/193670647-f831043d-6065-4363-bb10-e4a7cd14bac1.png)

**Comment by stevenjburrows** [comment]
I would like to pick this one up if it's okay

**Comment by Sammydepoj** [comment]
Hi, I can work on this. 
Kindly assign me

**Comment by Debajyoti14** [comment]
@stevenjburrows assigning it to you.
