### ISSUE TITLE
Add link contributing.md to official site

### ISSUE THREAD

**Issue by codeswithroh** [Clueless-Community/clueless-official-website#198]
![button](https://user-images.githubusercontent.com/77570394/193682279-3caff79a-7d8b-4b74-a534-b93d3b54fdca.png)
The button present here doesn't redirect to any particular link. Need to add [this](https://github.com/Clueless-Community/clueless-official-website/blob/main/CONTRIBUTING.md) as the link of that button.

**Comment by Debajyoti14** [comment]
We have changed this portion recently and ourselves took care of that. The changes are not deployed yet.
So closing this issue...
