### ISSUE TITLE
Back to top button on home page

### ISSUE THREAD

**Issue by snehafarkya** [Clueless-Community/clueless-official-website#200]
### Hey! I found your website quite interesting however as a web developer and designer, I think you should have a "Back to top" button or icon on home page. 

Also, I found a small UI error in your website. 
Take a look at the below screenshots  
#### Before: 

![image](https://user-images.githubusercontent.com/63949465/193748384-d44f85f2-5c67-46eb-b6c9-c903206be474.png)

#### After: 

![image](https://user-images.githubusercontent.com/63949465/193748492-4fd758cd-e14c-48f6-9ccd-e52bc8f99871.png)

### I would like to do this changes. Assign this issue to me!

**Comment by Debajyoti14** [comment]
@snehafarkya Any updates?

**Comment by snehafarkya** [comment]
Hey! The thing is when I'm doing changes in the code, its not reflecting on the website. I'm unable to change the code.

**Comment by Rajdip019** [comment]
> Hey! The thing is when I'm doing changes in the code, its not reflecting on the website. I'm unable to change the code.

The local server is not changing?

**Comment by durgeshm01722** [comment]
### Hey Admins, can you assign this task to me? I can try to resolve the UI issue and add the Back to Top Button.

**Comment by Debajyoti14** [comment]
@durgeshm01722 assigning it to you.
