### ISSUE TITLE
due to margin the social icons are not aligned

### ISSUE THREAD

**Issue by Ayush2020012016** [Clueless-Community/clueless-official-website#201]
the social icons are looking good with margin but for the small sized screen they are coming unaligned
![Hactoberfestimage2](https://user-images.githubusercontent.com/78146753/193764412-04037497-860e-400b-b6a8-6dd34fcff38e.png)

**I can change it to** 

![hactoberfestimage1](https://user-images.githubusercontent.com/78146753/193764456-00760e69-0eac-4b6d-8c5f-a2ccbec82d80.png)

please assign this to me.

**Comment by Rajdip019** [comment]
Yes go ahead @Ayush2020012016 . But make sure it doesn't break on desktop view. @Ayush2020012016

**Comment by Ayush2020012016** [comment]
ok thanks.

**Comment by Ayush2020012016** [comment]
i have a doubt will this count in the hactoberfest pr.

**Comment by Rajdip019** [comment]
Yes this will be counted as a hacktoberfest PR. @Ayush2020012016
