### ISSUE TITLE
*What is ClueLess?* section border bug in medium screen

### ISSUE THREAD

**Issue by pratham4434** [Clueless-Community/clueless-official-website#206]
The right side border is not visible at md-breakpoint
I can fix this issue, assign it to me please.

*Before*
![photo_2022-10-05_02-30-37](https://user-images.githubusercontent.com/91470779/193928866-2f6f36a8-8b9d-4805-9fd5-c4cafbea35e2.jpg)

*After*
![photo_2022-10-05_02-31-12](https://user-images.githubusercontent.com/91470779/193928881-ba016203-09a0-4771-bb6f-d60abaee8570.jpg)

**Comment by Rajdip019** [comment]
Sure @pratham4434 . Go ahead!
