### ISSUE TITLE
Spacing issue when we open sidebar. Below 'events', large space is left.

### ISSUE THREAD

**Issue by chetansingh-2** [Clueless-Community/clueless-official-website#209]

**Comment by chetansingh-2** [comment]
Hi
Please assign me the issue

**Comment by chetansingh-2** [comment]
![Uploading Screenshot_20221005-093124_Chrome.jpg…]()

**Comment by chetansingh-2** [comment]
![Screenshot_20221005-093124_Chrome](https://user-images.githubusercontent.com/109887534/193978960-d1a82c4d-aef6-40e1-be50-2d04882cea91.jpg)

**Comment by Rajdip019** [comment]
Go ahead and fix this issue. @chetansingh-2

**Comment by chetansingh-2** [comment]
> Go ahead and fix this issue. @chetansingh-2

This seems a browser issue. The site is working fine in other browsers. I tried on many other phones. I did not find any problem in the code. So I am closing the issue.
