### ISSUE TITLE
team blog page can be more responsive

### ISSUE THREAD

**Issue by Ayush2020012016** [Clueless-Community/clueless-official-website#216]
### Description

I can make it more responsive for mobile view

### Screenshots

![hactoberfest5](https://user-images.githubusercontent.com/78146753/194320365-0f32f8c4-3943-4ed5-b993-5578b7a90fee.png)
i can make it more responsive

### Additional information
please assign this to me

_No response_

**Comment by Rajdip019** [comment]
This is a hasnode blog. It's not made by us. @Ayush2020012016 So closing this issue.
