### ISSUE TITLE
The resource hub section breaks at breakpoint-md

### ISSUE THREAD

**Issue by Subhajitongit** [Clueless-Community/clueless-official-website#218]
### Description

I can fix this issue and make the component look more seemingly responsive. Could you please assign it to me?

### Screenshots

_How the component looks at full width_
![fullScreen](https://user-images.githubusercontent.com/90279748/194509934-3090be2f-3c6f-4785-b254-8be098d4b6bb.jpg)

_How the component looks at a mid breakpoint_
![midScreen](https://user-images.githubusercontent.com/90279748/194510159-305d5e12-d7a1-4a00-bd6a-c0272f0dce34.jpg)

**Comment by Subhajitongit** [comment]
@Rajdip019 please assign it to me

**Comment by Debajyoti14** [comment]
@Subhajitongit This thing looks fine. It's also not breaking in md breakpoint. Padding in X just changed.
SO, CLOSING THIS ISSUE.
