### ISSUE TITLE
Footer missing in /challenges-events route

### ISSUE THREAD

**Issue by vijay2249** [Clueless-Community/clueless-official-website#219]
### Description

Every route has a footer of same thing, but as there is not footer in /challenges-events route 

### Screenshots

![image](https://user-images.githubusercontent.com/65058877/194685113-b682f7c6-1e0b-43b5-a7aa-15b413c13595.png)

No footer in this route

**Comment by Saurav-Singh-Rauthan** [comment]
can i work on this?

**Comment by vijay2249** [comment]
I'm waiting for team members to assign it to me... :)

**Comment by Debajyoti14** [comment]
As that page is built with Notion which is a No-Code Technology.
It's not necessary to have a footer there.
For that closing this issue.
Thanks for pointing out.
