### ISSUE TITLE
Low quality image on signin page

### ISSUE THREAD

**Issue by rohan9024** [Clueless-Community/clueless-official-website#220]
### Description

Adding a new gif on the signin page instead of a low quality image which looks kind of decent.
I have designed the page. Can I go with this?

### Screenshots

Low Quality Image-
![image](https://user-images.githubusercontent.com/64919642/194699954-e5a25e9f-8fbf-423b-a9da-fe2decb2961c.png)

New GIF-

https://user-images.githubusercontent.com/64919642/194700247-1384040b-09ad-46ab-9b0c-b4ec14237368.mp4

### Additional information

I have also made this responsive according to the screen sizes.

**Comment by Satakshijain** [comment]
Hi , I would like to contribute to this . Please assign this issue to me

**Comment by Debajyoti14** [comment]
@rohan9024 This looks cool. Can you add some similar type of GIF with transparent background?

**Comment by rohan9024** [comment]
@Debajyoti14 The gif gets screwed. Can we go with current gif? And also I have replaced more images, can we replace it as well?

**Comment by rohan9024** [comment]
https://user-images.githubusercontent.com/64919642/194763565-e40cfc10-c27e-46d4-84b1-de887e24361e.mp4


https://user-images.githubusercontent.com/64919642/194763571-5ce7cb17-9aa2-4653-ada6-c6bf73c8cabf.mp4

**Comment by rahulkarda** [comment]
@Debajyoti14 who is assigned for this task?

**Comment by Debajyoti14** [comment]
@rohan9024 Assigning you.
Change the about us SVG as u shown.
The SVG u added login screen should have a transparent background.
Work on the changes requested.

**Comment by Debajyoti14** [comment]
@rohan9024 Are you working on this issue?

**Comment by rohan9024** [comment]
@Debajyoti14 working on it..... transparent background won't be possible .....can we go with the one I showed you?

**Comment by Debajyoti14** [comment]
@rohan9024 If not Gif, go with appropriate svg

**Comment by rohan9024** [comment]
@Debajyoti14 okay sure...can you please guide me on how should I commit changes and create a PR?

**Comment by Debajyoti14** [comment]
Guess you have already forked the GitHub Repo and make the changes in the main branch itself.
That's fine. Just push your code to the github in the main branch.
Then after pushing in the code in your repo,
you will be able to see the contribute button in the home screen of your forked repo.
Then tap contribute
, make a PR.

That's it we will merge it after reviewing the changes.

**Comment by rohan9024** [comment]
@Debajyoti14 Bro, I'm having this error.... can you please help?

![image](https://user-images.githubusercontent.com/64919642/195801088-f00b4a32-bc01-46ad-9f46-3201abea1b24.png)

**Comment by Debajyoti14** [comment]
This should help
https://stackoverflow.com/questions/5335197/gits-famous-error-permission-to-git-denied-to-user
