### ISSUE TITLE
explore button in projects enhancement

### ISSUE THREAD

**Issue by saimaheshtaduri** [Clueless-Community/clueless-official-website#225]
## **Is your feature request related to a problem? Please describe.**
whenever I click on the explore button of a project, I opens the github page of it in the same tab. I don't feel its so convenient this way.

## **Describe the solution you'd like**

I think opening the github pages in the new tab will be more efficient, and convenient to the end user.

**Comment by Athi223** [comment]
I'd like to contribute to this

**Comment by saimaheshtaduri** [comment]
@Debajyoti14
