### ISSUE TITLE
overlapping of project cards

### ISSUE THREAD

**Issue by saimaheshtaduri** [Clueless-Community/clueless-official-website#226]
### **Describe the bug**

The project cards are overlapping on each other.

### **To Reproduce**

1.go to https://www.clueless.tech/hacktoberfest
2. scroll down to projects section ( it works properly in mobiles)
---

### **Expected behaviour**

Better if the cards are separated from each other.

### **Media prove**

![Screenshot (39)](https://user-images.githubusercontent.com/53844369/194770039-1865fbd9-0edd-4273-8317-2ca7d30deeb0.png)

**Comment by Anish-Sarawgi** [comment]
I want to work on this issue.

**Comment by Debajyoti14** [comment]
@saimaheshtaduri Work on this.

**Comment by Debajyoti14** [comment]
@saimaheshtaduri Any update?

**Comment by rohan9024** [comment]
@Debajyoti14 If he's not working on it ..... I would love to contribute

**Comment by saimaheshtaduri** [comment]
I am working on it. Need some more time.

**Comment by rohan9024** [comment]
@Debajyoti14 please assign me this ......... I think he's not working on it

**Comment by Debajyoti14** [comment]
@rohan9024 assigned it to you

**Comment by rohan9024** [comment]
@Debajyoti14 Alright thanks buddy!

**Comment by rohan9024** [comment]
@Debajyoti14 Can I fix the design as well?
