### ISSUE TITLE
Logout button repositioning in mobile view & Logout confirmation dialog

### ISSUE THREAD

**Issue by SubxX** [Clueless-Community/clueless-official-website#228]
## **Is your feature request related to a problem? Please describe.**

* I think the logout button in the mobile menu doesn't look good also it creates an uneven gap between the menu & the button
* ![image](https://user-images.githubusercontent.com/51792949/194804038-c8ed4281-a4b3-40fc-9a79-6fd571eda38a.png)

---

## **Describe the solution you'd like**

I think we should move the logout button below the user name and also add a confirmation dialog.

I would like to work on this task
---

**Comment by Debajyoti14** [comment]
@SubxX Assigned you
