### ISSUE TITLE
[DOCS]: typo in the feature_request.yml file 

### ISSUE THREAD

**Issue by shashankbhatgs** [Clueless-Community/clueless-official-website#230]
### Description

There's a mistake in the wording in the feature_request.yml file template. Instead of 'clueless-official-website', 'Milan' is written. 
It seems that while creating the files, forgot to change the project name from Milan to clueless-official-website in the template. 

### Screenshots

![clueless](https://user-images.githubusercontent.com/76593166/194814165-23c8220b-8733-49c6-ba5b-259b20554d71.png)

### Additional information

I would like to work on this issue and correct the typo.

**Comment by Debajyoti14** [comment]
Sorry, but we are not accepting such typo fix PRs.
So, closing this
