### ISSUE TITLE
Adding Data Science in Resources Section

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/clueless-official-website#232]
## **Is your feature request related to a problem? Please describe.**

Data Science is an emerging field and we should include it in the resources section.
*

---

## **Describe the solution you'd like**

I want to add a Data Science section and related resources.
*

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

*

**Comment by Debajyoti14** [comment]
@rahulkarda We are not considering any issue of the resources section into the official website as it is built with Notion.
Still if you want to add such section, You can mail us with the resources or appeal to add a section.
Closing this issue.
