### ISSUE TITLE
[Enhancement] - Unclear "How to get Swags" guidelines on the Hacktoberfest page

### ISSUE THREAD

**Issue by AbirSantra** [Clueless-Community/clueless-official-website#234]
### Description

Hi, currently the guidelines on "How to get Swags" seem a bit unclear. Also, I would like to suggest some improvements.
1. The "If your PR got merged" text looks a bit too small and inconsistent with the design.
2. I would like to elaborate on the instructions a bit more and add more points if required. ( We can discuss what points can be added and which points can be elaborated)
3. Add a "Copy your profile URL from the address bar" point.
4. The "Comment your profile URL" point is very unclear since it does not tell the contributor where to comment.
5. The placement of the image makes the whole section look like it's kind left aligned. I would suggest adding proper spacing to make it more uniform for the design.

I would like to work on this section, particularly on the above-mentioned issues under Hacktoberfest. Please assign me this issue if approved and I will start my work at the earliest.
Thank you,
Abir Santra 

### Screenshots

![image](https://user-images.githubusercontent.com/78201921/194874860-0ebeaf57-1dec-4039-9329-0d68a976b49e.png)

**Comment by Debajyoti14** [comment]
@AbirSantra Go for it.

**Comment by AbirSantra** [comment]
> @AbirSantra Go for it.

Ok sure. I'll get started! Also, can you add the hacktoberfest labels to this issue?

**Comment by Debajyoti14** [comment]
okay👍

**Comment by Debajyoti14** [comment]
@AbirSantra What's the progress?

**Comment by AbirSantra** [comment]
> @AbirSantra What's the progress?
> 

I'll get started today. I had an exam. I'll share the new instructions with you today before implementing and we can discuss it.

**Comment by Debajyoti14** [comment]
@AbirSantra Sure

**Comment by Aman123lug** [comment]
@AbirSantra  can i also work on this?

**Comment by AbirSantra** [comment]
> @AbirSantra  can i also work on this?

Yeah definately but after I make my contribution. If you feel like you can improve it even further and the project admins approve of it, then feel free to raise an issue. 😃

**Comment by AbirSantra** [comment]
@Debajyoti14 What do you think of this content?


```
Section Header: How to win SWAGS?
Section Details: If your PR got successfully merged, you can earn points and have a chance to win awesome Swags! Make sure to follow the steps below carefully so that we can track your profile.
1. Star the Repository that you contributed to.
2. SignIn to your Clueless account. If you don't have an account yet, SignUp at clueless.tech (this will be a link) for free!
3. Go to your profile page from the menu at the top-right corner.
4. Copy your profile URL from the browser address bar.
5. Go back to your PR and comment your profile URL tagging the person who merged your PR.
6. You're all set!
```

Also, do you think we can implement a "Copy Profile URL" button on the user's profile page to make step 4 even better?
Let me know what you think.

**Comment by Debajyoti14** [comment]
@AbirSantra Great work. Go with the changes you specified.

But for now no need to add a copy button for Profile. One can simply copy it from Addressbar.

But make the changes you mentioned in the content and also do some changes in the ui so that it looks good

**Comment by AbirSantra** [comment]
> @AbirSantra Great work. Go with the changes you specified.
> 
> But for now no need to add a copy button for Profile. One can simply copy it from Addressbar.
> 
> But make the changes you mentioned in the content and also do some changes in the ui so that it looks good

Okay sure! I'll work on the UI and keep you updated!

**Comment by AbirSantra** [comment]
@Debajyoti14 What do you think of this?

**Comment by AbirSantra** [comment]
@Debajyoti14  What do you think of this?
I used a card with the same theme as the main website and changed it to a black background to match the theme of the Hacktoberfest page. I think this looks better than the previous design.
![image](https://user-images.githubusercontent.com/78201921/195875168-f3a7dc31-b048-4286-9318-a6aefb947ef6.png)
