### ISSUE TITLE
Adding links to the profiles in the Leaderboard 

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/clueless-official-website#235]
## **Is your feature request related to a problem? Please describe.**

Adding profile links to the leaderboard profiles so that users can directly see the profiles.

*

---

## **Describe the solution you'd like**

I'll add links to the profiles.
*

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

*

**Comment by arun-kushwaha04** [comment]
@Debajyoti14, can I work on adding this feature.

**Comment by Debajyoti14** [comment]
@rahulkarda our DB is not structured that way so that we can redirect from profile URL from the leaderboard page.
so closing this issue.

**Comment by rahulkarda** [comment]
Yeah I thought so, no worries.
