### ISSUE TITLE
Add Target as Blank in Export Button in in project card in hacktoberfest page.

### ISSUE THREAD

**Issue by devjain2309** [Clueless-Community/clueless-official-website#237]

**Comment by Rajdip019** [comment]
Go ahead and work on it. @devjain2309

**Comment by devjain2309** [comment]
@Rajdip019 I added this feature, please merge it.

**Comment by Debajyoti14** [comment]
@devjain2309 your pr is breaking the deployment
![image](https://user-images.githubusercontent.com/91759192/195079529-fdef78f5-e7c3-4d5c-9234-7ba66486bc7a.png)
Fix this error and commit further.

**Comment by RajKanani1206** [comment]
The Approach is completely wrong. Button tag cannot have target attribute. Should I go for this @Debajyoti14 ?

**Comment by Debajyoti14** [comment]
@RajKanani1206 Go for it👍

**Comment by Debajyoti14** [comment]
@RajKanani1206 yes

**Comment by RajKanani1206** [comment]
@saimaheshtaduri Sorry but its already completed and I have created PR for it.

**Comment by saimaheshtaduri** [comment]
@RajKanani1206 it's ok no worries. 🙂
