### ISSUE TITLE
[Bug] leaderboard is default going to bottom when refreshed in middle of the page

### ISSUE THREAD

**Issue by saimaheshtaduri** [Clueless-Community/clueless-official-website#238]
### **Describe the bug**

The leaderboard is default going to the bottom of the page, when the page is refreshed being in the page.

### **To Reproduce**

1. go to https://www.clueless.tech/hacktoberfest/leaderboard
2. scroll down a little bit down
3. now refresh the page

### **Expected behaviour**

It has to scroll to the top of the page when refreshed evrytime.

### **Media prove**

https://user-images.githubusercontent.com/53844369/194934310-8320f10e-480c-4eb4-ab7b-962a3143bd85.mp4

**Comment by KennethLeroy** [comment]
working on it

**Comment by Rajdip019** [comment]
Do you wanna work on it @saimaheshtaduri ?

**Comment by saimaheshtaduri** [comment]
Yes

**Comment by Rajdip019** [comment]
Okay you are assigned. @saimaheshtaduri
