### ISSUE TITLE
Add hover state on the resources cards

### ISSUE THREAD

**Issue by soustab10** [Clueless-Community/clueless-official-website#240]
### **Describe the bug**
Adding an hover state to the resources cards would make the UI better.

### **To Reproduce**

Steps to reproduce the error:

1. Visit https://clueless-resources.super.site/resources
2. Hover on resources
3. See error

---

### **Expected behaviour**

* Adding hover states to highlight the resource hovered by user.

---

### **Media prove**
![image](https://user-images.githubusercontent.com/95632583/195058688-2aa01787-7673-401d-886e-d692e2a2bcda.png)

I would like to work on this issue under hacktoberfest-label.

**Comment by Debajyoti14** [comment]
This page is not made with React.
It's built with notion which is a no-code tool.
So it can't be modified that way.
So closing this issue.
