### ISSUE TITLE
Update techstacks in the Techstack section of the profile 

### ISSUE THREAD

**Issue by soustab10** [Clueless-Community/clueless-official-website#242]
## **Is your feature request related to a problem? Please describe.**

Many techstacks (along with some important ones) are missing from the techstack dropdown menu, in the profile section. 

---

## **Describe the solution you'd like**

I would like to work upon it and add all the latest and popular technologies.

---

### **Additional context**
If approved, I would like to work on this issue.

*

**Comment by Debajyoti14** [comment]
@soustab10 Assigned you.

**Comment by Debajyoti14** [comment]
@soustab10 Any Updates?

**Comment by rohan9024** [comment]
@Debajyoti14 I would like to contribute ....... but I don't know what's he talking about😂

**Comment by Debajyoti14** [comment]
@rohan9024 In the add projects modal in the profile section
There is a field mp called Teck stack
Many techstack is missing there as it is a Autocomplete component from mui.

if you would like to contribute, I can assign you as @soustab10 is not responding

**Comment by rohan9024** [comment]
@Debajyoti14 hey can you please review my PR and issue?

**Comment by Debajyoti14** [comment]
@rohan9024 Done

**Comment by Debajyoti14** [comment]
If anyone still wants to contribute to add more unique Techstacks. They are welcome
