### ISSUE TITLE
Add Scroll to Top Button on Leaderboard Page

### ISSUE THREAD

**Issue by soustab10** [Clueless-Community/clueless-official-website#243]
## **Is your feature request related to a problem? Please describe.**
Leaderboard page has a lot of vertical scroll. So it would be better if a scroll to top button is present.

---

## **Describe the solution you'd like**
A scroll to top button similar to the main page will be implemented.

---

### **Additional context**

If approved I would like to work upon this issue.

**Comment by Debajyoti14** [comment]
@soustab10 Go for it.
Try to use the same scroll to top button used in homepage

**Comment by Debajyoti14** [comment]
@soustab10 What's the progress?

**Comment by Debajyoti14** [comment]
@rohan9024 assigning you

**Comment by rohan9024** [comment]
@Debajyoti14 close this issue
