### ISSUE TITLE
Add proper documentation to Guidelines Section

### ISSUE THREAD

**Issue by soustab10** [Clueless-Community/clueless-official-website#244]
### Description

Add proper contributing guidelines to the Guidelines section.

### Screenshots

![image](https://user-images.githubusercontent.com/95632583/195100717-8bf78c13-3dc0-4a1f-b374-3a391de156cf.png)

**Comment by Debajyoti14** [comment]
@soustab10 isn't the proper guidelines there after clicking the read more button?

**Comment by Debajyoti14** [comment]
Closing this issue for now. if required will reopen later on...
