### ISSUE TITLE
[Bug] Unnecessary Image Clicks - Accessibility Issue

### ISSUE THREAD

**Issue by RajKanani1206** [Clueless-Community/clueless-official-website#248]
### **Describe the bug**
Unnecessary image click with href. Also, Some images still don't have alt tags, which causes a low accessibility score for the site. 

---

### **To Reproduce**

1. Go to [https://www.clueless.tech/hacktoberfest](https://www.clueless.tech/hacktoberfest)
2. scroll down a little bit and click on the image of how to get swags section.
3. See error

---

### **Expected behaviour**

Image should not be clickable.

---

### **Media prove**

https://user-images.githubusercontent.com/104709529/195176003-475058d3-42e5-43cf-8ba2-e2fd794ce2de.mp4

---

### **Additional context**

If approved I would like to work upon this issue and can also update image alt attribute globally across the project.

**Comment by RajKanani1206** [comment]
Is this how it works ? No assignees !!! Direct Submissions and approved by maintainers that too with half the problem statement resolved !!!!

**Comment by Debajyoti14** [comment]
@RajKanani1206 Are you talking about this issue ticket?
There might be some confusion regarding this issue.
We will take care of this things in the future.
Thanks for pointing out
