### ISSUE TITLE
[Feature] - Search feature to filter leaderboard

### ISSUE THREAD

**Issue by its-ayush-07** [Clueless-Community/clueless-official-website#249]
## **Is your feature request related to a problem? Please describe.**

* On the leaderboard page, it's time-consuming for a contributor to check their own points, among a vast list of 250+ contributors.

---

## **Describe the solution you'd like**

* A **Search** feature to filter the leaderboard by GitHub username, for user convenience.

---

### **Additional context**

* I'd like to work on this issue

**Comment by Debajyoti14** [comment]
@its-ayush-07 As this leaderboard is ocassional. We think that people just can search themselves with ctrl+f. So, closing this issue for now.
