### ISSUE TITLE
Enhance the Readme

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#252]
### Description

Enhance the Readme for adding the maintainers.
For this Repo add @Debajyoti14 @Rajdip019 as Maintainers.
.
.
.
For Reference check this :-
https://github.com/Clueless-Community/web-ui-kit/blob/main/README.md

### Screenshots

![image](https://user-images.githubusercontent.com/91759192/195255496-a9a9d3c3-bbc6-42bd-8115-88c434b93211.png)

**Comment by najeebkp** [comment]
hi @Debajyoti14 please assign this to me

**Comment by RajKanani1206** [comment]
I would like to work on it.

**Comment by Debajyoti14** [comment]
@najeebkp Go for it.
