### ISSUE TITLE
Can't save without deployment URL while adding Projects.

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#253]
#### While adding projects the deployed website URL field should be optional in the profile page.

now the save button remains disabled without the deployed URL.

### Screenshots

![Screenshot from 2022-10-11 00-17-22](https://user-images.githubusercontent.com/91759192/195256045-d23ac993-8e52-4566-812c-f3baf400d638.png)

**Comment by RajKanani1206** [comment]
I would like to work on it.

**Comment by Debajyoti14** [comment]
@RajKanani1206 Assigned you.

**Comment by RajKanani1206** [comment]
@Debajyoti14 

![image](https://user-images.githubusercontent.com/104709529/195261966-c8807d32-14df-4b19-924d-0c37c1d8e8f4.png)

Also, there is another bug, It's working without Project Name. Fixing that too.

**Comment by Debajyoti14** [comment]
@RajKanani1206 Thanks for finding. Fix it.

**Comment by RajKanani1206** [comment]
@Debajyoti14 Fixed already and created PR too.
