### ISSUE TITLE
Sponsor image seems to big for mobiie view

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#258]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/195269780-b9cdf040-dc39-4072-8187-f5e1d173ae03.png)

**Comment by RajKanani1206** [comment]
Working on it.

**Comment by Debajyoti14** [comment]
@RajKanani1206 Wait for the PRs being reviewed
