### ISSUE TITLE
Enhance Login Screen UI 

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#259]
### Description

Enhance this Login screen UI

### Screenshots

![image](https://user-images.githubusercontent.com/91759192/195271897-b80b6ef8-6673-4c29-a8b6-ed94818f74ff.png)

**Comment by Anuran12** [comment]
I would like to work on this

**Comment by Anuran12** [comment]
Please assign it to me @Debajyoti14

**Comment by Debajyoti14** [comment]
@Anuran12 Share your figma design before proceeding with code.
Assigning it to you.

**Comment by tanishk-23** [comment]
@Debajyoti14 can I also work on this issue?

**Comment by Debajyoti14** [comment]
@Anuran12 is working on it. After him I can assign it to you @tanishk-23

**Comment by Anuran12** [comment]
@Debajyoti14 you can unassign me . because i an not familiar with figma. so i am not good for this issue .

**Comment by Debajyoti14** [comment]
@tanishk-23 assigned you

**Comment by rohan9024** [comment]
@Anuran12 Can I join you bro? (if you don't mind)

**Comment by Anuran12** [comment]
@rohan9024 I am not working on this project now... you can ask @tanishk-23

**Comment by rohan9024** [comment]
@tanishk-23 Can I join you bro? (if you don't mind)

**Comment by tanishk-23** [comment]
@Debajyoti14 I have to redesign the Login Screen or just do the changes in the existing one?
I have designed a new design just have a look.

https://www.figma.com/file/TINupPpnQv0E0UscehIjnR/Web-Login?node-id=0%3A1

**Comment by Debajyoti14** [comment]
@tanishk-23 The design looks very cool.
You can go with it.
Just make sure the navbar and the color combination remains intact.
Good work

**Comment by tanishk-23** [comment]
@Debajyoti14 why this issue has been closed?

**Comment by Debajyoti14** [comment]
Someone has changes the login screen image
![image](https://user-images.githubusercontent.com/91759192/195996736-d439498e-1920-47ff-82c6-9d5f46e6fecb.png)
This looks like this now.
If you want to enhance the UI further. You surely can.
But share the Figma Design before developing it @tanishk-23

**Comment by tanishk-23** [comment]
> @Debajyoti14 I have to redesign the Login Screen or just do the changes in the existing one? I have designed a new design just have a look.
> 
> https://www.figma.com/file/TINupPpnQv0E0UscehIjnR/Web-Login?node-id=0%3A1

I have shared it before

**Comment by Debajyoti14** [comment]
@tanishk-23 If you can, then implement this UI fully.
Just dont change the Navbar

**Comment by rohan9024** [comment]
@Debajyoti14 @tanishk-23 I can help you if you need🙋🏻‍♂️

**Comment by Debajyoti14** [comment]
@rohan9024 Discuss with @tanishk-23
if he permits, You can both can do the work alongside.

**Comment by rohan9024** [comment]
@Debajyoti14 can I enhance the resources page?

**Comment by Debajyoti14** [comment]
@rohan9024 There is nothing to code in Resources Page as it is built with Notion.

If you want to add Resources in the Resources section, You can all the links of the resources in a gDoc and mail it to us.

**Comment by Debajyoti14** [comment]
@tanishk-23 What's the update?

**Comment by rohan9024** [comment]
@Debajyoti14 if he's not active .....I would love to design the login page as per the figma file

**Comment by rohan9024** [comment]
@Debajyoti14 he's not working on it .......assign me I'll redesign according to the figma file

**Comment by rohan9024** [comment]
@Debajyoti14 Alright, thanks buddy!

**Comment by Debajyoti14** [comment]
@rohan9024 What's the update?

**Comment by rohan9024** [comment]
@Debajyoti14 I was resolving the branch conflict before ....now working on the login page

**Comment by rohan9024** [comment]
@Debajyoti14 bro brooooo
I need ur help

**Comment by rohan9024** [comment]
The UI looks very incomplete ..... can you suggest some ideas?

![image](https://user-images.githubusercontent.com/64919642/196880623-6f41d70a-2513-472a-9a02-9b9884735c08.png)

**Comment by Debajyoti14** [comment]
@rohan9024 Can you add a blue splash behind the image on the left side?

Make sure it's fluidly responsive

Then I guess it will look great

**Comment by rohan9024** [comment]
@Debajyoti14 ohhh alright and anything else??

**Comment by Debajyoti14** [comment]
@rohan9024 Add blue splash not on the image but on the text.
Try to experiment a bit , in case it looks better
