### ISSUE TITLE
Add Elevation on Hover in Team Member Cards

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#269]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/195997238-848167eb-3668-4d4e-b008-6df4e25b7452.png)

**Comment by yashsarnaik22** [comment]
hey @Debajyoti14 can I do this?
Please assign it to me.

**Comment by Debajyoti14** [comment]
@yashsarnaik22 Go for it.

**Comment by yashsarnaik22** [comment]
Thank You!

**Comment by yashsarnaik22** [comment]
@Debajyoti14 can you please tell me in which directory or file the code card components is saved? 
is it an automized element?

**Comment by Debajyoti14** [comment]
@yashsarnaik22 ProfileCard component in about us page

**Comment by yashsarnaik22** [comment]
okay thank you!

**Comment by Kingshuk3006** [comment]
@yashsarnaik22 are you still working on it??

**Comment by rohan9024** [comment]
@Debajyoti14 please assign me if anyone is not working on it

**Comment by soustab10** [comment]
This issue has been fixed by #348
