### ISSUE TITLE
Scale up while hovering on social buttons

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#270]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/195997468-335e8925-d751-4f20-89cf-37a7370382c4.png)

**Comment by ankitkumar0622** [comment]
hii , can you assign me this task , i would love to work on it.

**Comment by Debajyoti14** [comment]
@ankitkumar0622 Assigning you.

**Comment by rmgb05** [comment]
Can i work on this issue .. If available ..

**Comment by Debajyoti14** [comment]
after @ankitkumar0622 I can assign you @rmgb05

**Comment by Debajyoti14** [comment]
@ankitkumar0622 What's the progress?

**Comment by ankitkumar0622** [comment]
I have almost finished , it will be done by tomorrow noon , sorry for the delay . @Debajyoti14

**Comment by Debajyoti14** [comment]
@ankitkumar0622 no worries 😇

**Comment by Debajyoti14** [comment]
@ankitkumar0622 any updates?
