### ISSUE TITLE
Improve readme.md

### ISSUE THREAD

**Issue by money8203** [Clueless-Community/clueless-official-website#275]
### Description

Please add more precise details about the projects like how to get started what to do where to contribute . It will be helpful for folks who are new to open source and if all the instructions will be displayed properly and clearly i think beginners can also contribute to some moderate level projects

**Comment by Debajyoti14** [comment]
@money8203 What information you would like to add?

**Comment by money8203** [comment]
I'll suggest to implement a video tutorial on how to install the project environment locally  so that one can clearly understand the process and be able to give feedback if there is any error/bug in the project and it will ease the toughness of project and will become a beginner friendly project.

**Comment by Debajyoti14** [comment]
It not a complex project, just have to copy paste the keys into the .env file and the guide is already there
https://github.com/Clueless-Community/clueless-official-website/blob/main/CONTRIBUTING.md
So, closing this issue.
