### ISSUE TITLE
Fix the Overlapping videos in How internet works page

### ISSUE THREAD

**Issue by sshiwangi** [Clueless-Community/clueless-official-website#279]
### Description

The videos are overlapping and also not align in the How internet works page. I would like to fix this issue.

### Screenshots

![clueless](https://user-images.githubusercontent.com/77545230/196053652-76f7a3ea-39cb-44af-ad21-32dfddc88630.png)

**Comment by sshiwangi** [comment]
@Debajyoti14 Please assign me this issue.

**Comment by Debajyoti14** [comment]
@sshiwangi This page is built with Notion which is a no code tool. So closing this issue
