### ISSUE TITLE
Fix HTML page Responsiveness

### ISSUE THREAD

**Issue by surbhi400** [Clueless-Community/clueless-official-website#280]
### Description

The HTML page in the web development section is not responsive for bigger devices. I will improve it's responsiveness.

### Screenshots

![2022-10-17 (2)](https://user-images.githubusercontent.com/77582783/196053774-33329b0b-1427-4d8c-9436-e441fe40df93.png)

**Comment by kasturi019** [comment]
Please assign me this issue! I can work on it

**Comment by surbhi400** [comment]
@Debajyoti14 I created this issue so please assign it to me.

**Comment by Debajyoti14** [comment]
@surbhi400 This page is built with Notion which is a no code tool. so closing this issue
