### ISSUE TITLE
Replace images with gifs 

### ISSUE THREAD

**Issue by rohan9024** [Clueless-Community/clueless-official-website#282]
### Description

Can  I replace Low quality Images on hacktoberfest page with animated gifs and improve styling?
If yes, please assign me.

### Screenshots
The meditating image currently being used- 

![image](https://user-images.githubusercontent.com/64919642/196133874-a24ba27f-1ad3-44b5-a4ee-95f46586fd46.png)

After adding gif-
https://user-images.githubusercontent.com/64919642/196132949-a5258551-faaf-401e-9221-c71590669d71.mp4

### Additional information

Also, I would fix the designing, text alignment, text size, responsiveness as well

**Comment by Debajyoti14** [comment]
@rohan9024 Adding a lot of gifs is not a good way as it becomes too distracting for a user to surf the website. it's also not going with the theme that well. So, closing this issue.

**Comment by rohan9024** [comment]
@Debajyoti14 or maybe adding different images?
