### ISSUE TITLE
Small UI fix in the contact us page

### ISSUE THREAD

**Issue by codeswithroh** [Clueless-Community/clueless-official-website#283]
### Description

The alignment of the form and the picture is too close in the [contact us](https://www.clueless.tech/contact-us) page. Need proper spacing between the two

### Screenshots

![contact us](https://user-images.githubusercontent.com/77570394/196226237-a5e291e7-8b4d-4cb5-bc00-5bc19a7abfe5.png)

**Comment by Debajyoti14** [comment]
@codeswithroh assigning you
