### ISSUE TITLE
Adding hover effects on NavLinks

### ISSUE THREAD

**Issue by rohan9024** [Clueless-Community/clueless-official-website#291]
Before adding hover- 

https://user-images.githubusercontent.com/64919642/196418111-9788bce9-139d-438c-94b3-b05756767daf.mp4

After adding hover- 

https://user-images.githubusercontent.com/64919642/196420786-5d7355f8-753c-4240-9688-70cc0dd99b51.mp4

**Comment by rohan9024** [comment]
@Debajyoti14 please assign I have already implemented this

**Comment by Debajyoti14** [comment]
@rohan9024 assigned you
