### ISSUE TITLE
Change the Why you should Contribute Image

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#292]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/196420771-06da7a17-b922-4339-aa23-224c9377c986.png)

**Comment by durgeshm01722** [comment]
@Debajyoti14 Can you assign this to me?

**Comment by durgeshm01722** [comment]
Fixed this issue in PR no - #288 

![Screenshot 2022-10-18 182700](https://user-images.githubusercontent.com/85431456/196437038-d903b044-82ea-4523-bb9b-f15cf47d1de8.png)

**Comment by durgeshm01722** [comment]
Thanks 🙌

**Comment by Sejal-shh** [comment]
Can I solve this please ?

**Comment by Debajyoti14** [comment]
@Sejal-shh sorry the problem is already fixed. so closing this issue
