### ISSUE TITLE
Add <a> links in Sponsors

### ISSUE THREAD

**Issue by soustab10** [Clueless-Community/clueless-official-website#305]
## **🐞 Bug Report**
Add anchor tags to redirect to the page of sponsors
### **Describe the bug**

Community partners should have <a> tags such that they direct the user to the main webpage/social handle of the partner when hovered.

### **Screenshots**
![image](https://user-images.githubusercontent.com/95632583/196779418-5ce1ce45-a7bc-4f5f-b5f3-55628db35b3f.png)

If approved, I would like to work on this issue.

**Comment by NeerajGartia21** [comment]
I want to work on this issue.
Can you please assign it to me?

**Comment by Debajyoti14** [comment]
@soustab10 Assigning you

**Comment by soustab10** [comment]
Can you provide the links of the community partners to which they should redirect?
@Debajyoti14

**Comment by Debajyoti14** [comment]
For Metafy https://metafy.social/

For Flutter Kolkata http://www.flutterkolkata.dev

@soustab10

**Comment by nik132-eng** [comment]
if this is unresolved i want to contribute. Can you please assign me this issue?

**Comment by soustab10** [comment]
I am working on it. PR will beade soon. Thanks.

**Comment by soustab10** [comment]
> For Metafy https://metafy.social/
> 
> For Flutter Kolkata http://www.flutterkolkata.dev
> 
> @soustab10

is it okay if add the website link of iNeuron. @Debajyoti14 If yes provide the link for the same.

**Comment by Debajyoti14** [comment]
@soustab10 Add that 👍

**Comment by soustab10** [comment]
> @soustab10 Add that 👍

Please provide the link of their website/socials?
