### ISSUE TITLE
Add hover states on Social icons

### ISSUE THREAD

**Issue by soustab10** [Clueless-Community/clueless-official-website#306]
### **Describe the bug**

* Add hover states to social icons in accordance with the theme of the app

---

![image](https://user-images.githubusercontent.com/95632583/196780205-11a3ee0c-a2c4-4617-be0a-71632889673d.png)

If approved, I would like to work on this issue.

**Comment by NeerajGartia21** [comment]
I want to work on this issue.
Can you please assign it to me?

**Comment by Debajyoti14** [comment]
@soustab10 Go for it

**Comment by soustab10** [comment]
@Debajyoti14 Please send the credentials. I have mailed to the said mail.
