### ISSUE TITLE
Fix this Image in Dark Mode

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#307]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/196813282-e0f6cfb7-b1aa-46ff-9e14-ac941b6bdc52.png)

**Comment by bbsdevloper** [comment]
can I solve this issue? @Debajyoti14

**Comment by durgeshm01722** [comment]
Hey, I fixed this issue in PR no - #321
