### ISSUE TITLE
Fix Guidelines Section in Dark Mode

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#308]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/196813618-4aa2d78e-c430-4b4c-bc56-7a8e845abb73.png)

**Comment by soustab10** [comment]
I would like to work on this issue.

**Comment by Debajyoti14** [comment]
@soustab10 Assigned you

**Comment by Debajyoti14** [comment]
@soustab10 What's the Update?

**Comment by soustab10** [comment]
> @soustab10 What's the Update?

working on it. PR will be made soon.

**Comment by Debajyoti14** [comment]
@soustab10 Any Progress?

**Comment by gaut2003** [comment]
Please assign this to me is possible. @Debajyoti14 Since @soustab10 has not responsed.

**Comment by Debajyoti14** [comment]
@gaut2003 assigned you

**Comment by Debajyoti14** [comment]
@gaut2003 any updates???
