### ISSUE TITLE
Fix LoginScreen in Darkmode

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#310]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/196814343-fdd615fc-5490-46e6-879f-d593eb326fae.png)

**Comment by Kingshuk3006** [comment]
I want to work in this issue

**Comment by Debajyoti14** [comment]
@mohitkumaragrawal assigned you

**Comment by nik132-eng** [comment]
if this is unresolved i want to contribute. Can you please assign me this issue?

**Comment by Debajyoti14** [comment]
@nik132-eng assigned you.

**Comment by Debajyoti14** [comment]
@nik132-eng Stop working on this as the total UI of Lockscreen is revamped.
