### ISSUE TITLE
Fix Landing Page in Dark Mode

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#311]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/196814964-afde3705-e37e-4d30-9654-9a89155901ed.png)

**Comment by bbsdevloper** [comment]
I want to use some LottieFiles dark animation over there can you assign this to me..

**Comment by Debajyoti14** [comment]
@bbsdevloper go for it

**Comment by bbsdevloper** [comment]
![image](https://user-images.githubusercontent.com/99157367/196941301-c7f19bcf-18f5-4f83-bae4-dbeec6b8208b.png)
can you chose ant one or should i go with my choics

**Comment by Debajyoti14** [comment]
@bbsdevloper Actually we want to keep the previous image itself and the white edges has been fixed. So, closing this issue.
