### ISSUE TITLE
Fix Icons for Dark theme

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#312]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/196815283-22ce0012-7c88-4c9f-b6f4-ca3ebc07c37a.png)

**Comment by sutirthverma** [comment]
Hey I would love to work on this issue, can you assign it to me?

**Comment by RajKanani1206** [comment]
I will do it. Please assign it to me.

**Comment by durgeshm01722** [comment]
Hey, I fixed this issue in PR no - #324

**Comment by RajKanani1206** [comment]
Not perfect, i will be adding more appropriate solution soon.

**Comment by Debajyoti14** [comment]
@RajKanani1206 You are welcome to add any positive changes
