### ISSUE TITLE
Change Footer Link URL

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#313]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/196815626-b4e16664-d8d1-48e0-9aa2-ee5ef4e9217a.png)

**Comment by LucianeFernandesRoque** [comment]
can I assigne me this issue?

**Comment by LucianeFernandesRoque** [comment]
Hi! I'ts my PR 'https://github.com/Clueless-Community/clueless-official-website/pull/318'

**Comment by Debajyoti14** [comment]
@LucianeFernandesRoque will review

**Comment by LucianeFernandesRoque** [comment]
> @LucianeFernandesRoque will review 

Thx

**Comment by LucianeFernandesRoque** [comment]
ok

> @LucianeFernandesRoque Reverted your PR. Please make another PR by adding proper URL to proper Links. You added wrong links in the previous PR

ok

**Comment by LucianeFernandesRoque** [comment]
> ok
> 
> > @LucianeFernandesRoque Reverted your PR. Please make another PR by adding proper URL to proper Links. You added wrong links in the previous PR
> 
> ok

Hi @Debajyoti14  I open new PR, u can verify please? thx
