### ISSUE TITLE
Fix contact us form for Dark Mode

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#314]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/196815918-d67fa6d7-2f78-48d9-9e08-d64029dd2576.png)

**Comment by chibuh** [comment]
Hey, can you assign this issue?
Adding a screenshot, please check if any other changes required.
![image](https://user-images.githubusercontent.com/74678752/196828906-0d7b8568-0d40-4c29-bcf0-fd13ab35c5e5.png)

**Comment by Debajyoti14** [comment]
@chibuh looks good.
assigned it to you
