### ISSUE TITLE
Fix FAQ accordion in Dark Mode

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#315]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/196816166-94fe4deb-49bf-4763-b239-f6cc254eb4fa.png)

**Comment by RajKanani1206** [comment]
I will do it. Please assign it to me.

**Comment by Kingshuk3006** [comment]
Assign it  to me

**Comment by Debajyoti14** [comment]
@RajKanani1206 assigned you

**Comment by Debajyoti14** [comment]
@RajKanani1206 Any Progress?

**Comment by RajKanani1206** [comment]
Working on it. Will update progress soon.
