### ISSUE TITLE
Fix Leaderboard in Dark mode

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#316]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/196816635-fe277da9-4521-4310-8e9c-a9de0564efd6.png)

**Comment by RajKanani1206** [comment]
I will do it. Please assign it to me.

**Comment by Debajyoti14** [comment]
@RajKanani1206 Okay Will review the PR

**Comment by RajKanani1206** [comment]
@Debajyoti14 I have closed the PR. Let me know once leaderboard is resolved.

**Comment by Debajyoti14** [comment]
@RajKanani1206 Leaderboard is fixed. You can reopen it now.

**Comment by RajKanani1206** [comment]
@Debajyoti14 I created new PR, you can check it now.
