### ISSUE TITLE
Fix Profile Card Design For Dark Mode

### ISSUE THREAD

**Issue by Kingshuk3006** [Clueless-Community/clueless-official-website#322]
### Description

Make the design more Eye soothing.
Assign Me for the Issue

### Screenshots

![image](https://user-images.githubusercontent.com/93638401/196932706-22913c3d-a90a-4a8b-a177-1b17cd61cf6a.png)

**Comment by Debajyoti14** [comment]
@Kingshuk3006 Closing this issue as already resolved
