### ISSUE TITLE
Resource Page

### ISSUE THREAD

**Issue by devjain2309** [Clueless-Community/clueless-official-website#333]
In the navbar, all the elements have the same property except the resource page.
By elaborating on this sentence I would like to share some images.
![Screenshot (37)](https://user-images.githubusercontent.com/69387311/197030633-7a5e8a4e-4f2c-4595-a92a-f4ac05269286.png)
![Screenshot (38)](https://user-images.githubusercontent.com/69387311/197030645-afc07119-2935-4e4f-9dac-117ebb835040.png)

need to add a similar navbar on the resource page to make a good user experience.

**Comment by chibuh** [comment]
Do you want the same navBar ins resource section? Please assign thi task to me.

**Comment by Debajyoti14** [comment]
@devjain2309 The resources website is built with a no-code tool called Notion. It doesn't permit such customisation. so, closing this issue.
