### ISSUE TITLE
update the swags info 

### ISSUE THREAD

**Issue by saimaheshtaduri** [Clueless-Community/clueless-official-website#336]
## **Is your feature request related to a problem? Please describe.**
At present, information about the swags is not updated.

## **Describe the solution you'd like**
Update the information in the Rewards&Swags section, and also ReadMore button is of no use now, add a github link to it.

**Comment by nik132-eng** [comment]
can you assign me this issue?

I want to verify is this thing to add on main website?
![image](https://user-images.githubusercontent.com/77881638/197342564-470cc4e7-f268-4c40-b353-4eea1fd6a27e.png)

**Comment by Debajyoti14** [comment]
@saimaheshtaduri just add this link to the button https://clueless-resources.super.site/hacktoberfest/how-to-get-eligible-for-swags
This will do it
