### ISSUE TITLE
add sponser links in home

### ISSUE THREAD

**Issue by saimaheshtaduri** [Clueless-Community/clueless-official-website#337]
## **Is your feature request related to a problem? Please describe.**
At present, in sponsers section, there's nothing happening hovering over sponsers.

## **Describe the solution you'd like**
on clicking the sponsers, route to their relevant pages.

**Comment by Hrx4** [comment]
Hey i can do it , btw by doing this can i get points in leaderboard?

**Comment by Debajyoti14** [comment]
@saimaheshtaduri Closing this issue as it is already listed.
