### ISSUE TITLE
Fix uneven height of Project Cards

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#340]
### Description

Enhance the card like all the height of the cards remain same irrespective of the card content

### Screenshots

![image](https://user-images.githubusercontent.com/91759192/197350573-9c1e84af-9935-4336-9a2b-9d4772ffe9a0.png)

**Comment by nitoC** [comment]
can you assign this to me?

**Comment by itsmeAnubhab** [comment]
i would like to fix this.

**Comment by Debajyoti14** [comment]
@nitoC assigned you

**Comment by Ishikasaraf20** [comment]
hey @Debajyoti14 can you assign this issue to me i can work on it
