### ISSUE TITLE
Fix the Hacktoberfest background colour for dark theme

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#341]
### Description

Add a different background for the Hacktoberfest banner for dark theme so that it looks great 

### Screenshots

![image](https://user-images.githubusercontent.com/91759192/197350615-04c89bcd-516f-4d7d-ae50-e69c00804293.png)

**Comment by SainathPoojary** [comment]
Hey @Debajyoti14, I want to work on this. Please assign it to me

**Comment by itsmeAnubhab** [comment]
i would like to work on it.

**Comment by mnosov622** [comment]
Hello!

@Debajyoti14 I would love to work on this issue :)

Could you please assign it to me ?

**Comment by Debajyoti14** [comment]
Assigning @SainathPoojary as he commented first

**Comment by Ishikasaraf20** [comment]
hey @Debajyoti14 can you assign this issue to me i can work on it

**Comment by SainathPoojary** [comment]
Hey @Debajyoti14, I have tried some colours, which one do you prefer or is there a suggested background from your side?

### Existing

| Dark Theme | Light Theme |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/53347682/197382480-4bb0667c-bf07-43b7-b823-5d796a6744fe.png)     | ![image](https://user-images.githubusercontent.com/53347682/197382497-949ad623-ae4a-4ddd-817a-d0db1d858fb9.png)|

### New Colors

| Dark Theme | Light Theme |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/53347682/197380813-509f383a-b527-4ef7-a652-7b73cfd612bc.png)      | ![image](https://user-images.githubusercontent.com/53347682/197380829-fb89de94-bdf1-42cd-82a5-f1f39a362dac.png)       |
| ![image](https://user-images.githubusercontent.com/53347682/197382051-e0ee1fcf-20ba-45fc-aae4-87a07d7e2b22.png)   | ![image](https://user-images.githubusercontent.com/53347682/197382067-6bab347d-9ea5-456b-9ed1-95ae7cb67739.png)        |
|![image](https://user-images.githubusercontent.com/53347682/197382448-40536360-7c4c-451e-83d3-e74d2fe4384f.png)|![image](https://user-images.githubusercontent.com/53347682/197382420-8b022e33-be2f-4c07-a126-68109123fe77.png)    |

**Comment by Debajyoti14** [comment]
@SainathPoojary Keep the existing colour for light theme but change the colour for dark theme the 2nd one you mentioned

**Comment by SainathPoojary** [comment]
Hey @Debajyoti14, I have raised a PR, Please review it and do let me know if you need any changes.
