### ISSUE TITLE
issue: login page in dark mode

### ISSUE THREAD

**Issue by itsmeAnubhab** [Clueless-Community/clueless-official-website#343]
### Description

The image in the login page doesnot fit well for the dark mode.

### Screenshots

![loginissue](https://user-images.githubusercontent.com/91974827/197353172-0eec759a-7d52-4fcf-882d-e0302f3a48f0.PNG)

### Additional information

I would like to work on this issue.

**Comment by Debajyoti14** [comment]
@itsmeAnubhab Closing this issue as the UI is already updated.
