### ISSUE TITLE
Set default theme as Light Theme

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#346]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/197355530-f05609c4-48a8-4305-8783-9ad327bffa25.png)

**Comment by J0SAL** [comment]
Please assign this to me

**Comment by kashish0604** [comment]
hey @Debajyoti14 can you assign this issue to me i can work on it

**Comment by Debajyoti14** [comment]
@J0SAL Will review your PR
