### ISSUE TITLE
Error in the guidline section of hacktoberfest page

### ISSUE THREAD

**Issue by itsmeAnubhab** [Clueless-Community/clueless-official-website#355]
### Description

In the guidlines section of the hacktoberfest page, the contents of "why you should contribute" is written all over again instead of the actual guidlines.

### Screenshots

![guidlines](https://user-images.githubusercontent.com/91974827/197362452-0e9f750e-dd47-4bcd-afc6-f153b33c6a19.PNG)

### Additional information

I would like to fix this issue.

**Comment by Debajyoti14** [comment]
@itsmeAnubhab already same issue is listed below. So, closing this one
