### ISSUE TITLE
Add scroll to top button on the hacktoberfest page

### ISSUE THREAD

**Issue by itsmeAnubhab** [Clueless-Community/clueless-official-website#356]
### Description

Hacktoberfest page doesnot have a scroll to top button. So it needs one.

### Additional information

I would like to add the button.

**Comment by Debajyoti14** [comment]
@itsmeAnubhab assigned you

**Comment by snehasish-pathak** [comment]
**I can add scroll to top button on the hacktoberfest page , please assign this issue to me.**
