### ISSUE TITLE
Profile page dark mode issue

### ISSUE THREAD

**Issue by itsmeAnubhab** [Clueless-Community/clueless-official-website#360]
### Description

The background of the profile page doesnot match the dark theme. The texts are white but the background is also white, so there's no contrast and the text are not visible.

### Screenshots

![logindark](https://user-images.githubusercontent.com/91974827/197379299-57d6c258-f1a7-471a-9173-56e5bdc1592a.PNG)

### Additional information

I would like to solve this issue.

**Comment by Debajyoti14** [comment]
@itsmeAnubhab assigned you
