### ISSUE TITLE
add link to clueless logo in footer

### ISSUE THREAD

**Issue by saimaheshtaduri** [Clueless-Community/clueless-official-website#361]
## **Is your feature request related to a problem? Please describe.**
At present, the clueless logo in footer isn't taking anywhere.

## **Describe the solution you'd like**
I would prefer that logo in the footer redirect to the home page.

**Comment by saimaheshtaduri** [comment]
@Debajyoti14

**Comment by Debajyoti14** [comment]
@saimaheshtaduri assigned you
