### ISSUE TITLE
Add target=_blank in Community Partners & Sponser Images

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#367]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/197402519-1f98506e-6773-495e-900c-97415a949e8b.png)

**Comment by Anish-Sarawgi** [comment]
Interseted

**Comment by Debajyoti14** [comment]
@Anish-Sarawgi assigned you

**Comment by Anish-Sarawgi** [comment]
@Debajyoti14 i have sent a PR. Please have a look.
