### ISSUE TITLE
Add a option clear the search input in Leaderboard search

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#368]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/197402663-1c0e5741-5386-477f-aedc-e066cdf0a181.png)

**Comment by JawHawk** [comment]
Hey I can work on this , kindly guide me to the leaderboard page as I am unable to find it on the website.

**Comment by Debajyoti14** [comment]
@JawHawk assigned you and go to https://www.clueless.tech/hacktoberfest/leaderboard
You will find the leaderboard

**Comment by JawHawk** [comment]
I did the button and its functioning as wanted. Just inform if you want to change the text ( "Clear" ) or anything else. If you have no issues, I will proceed to PR.
![clueless](https://user-images.githubusercontent.com/86140365/197415925-95c8507d-0fdf-4206-999d-92a6cfd267a5.PNG)

**Comment by JawHawk** [comment]
I did the button and it is functioning as wanted. Just inform if you want to change the text ( "Clear" ) or anything else. If you have no issues, I will proceed to PR.
![clueless](https://user-images.githubusercontent.com/86140365/197416035-25ab45e0-b6d4-4f3f-861c-e6eed73b7ea9.PNG)

**Comment by Debajyoti14** [comment]
@JawHawk The text Clear would work. What we want is after clicking clear not only the text disappears but also the leaderboard resets to all.So that user doesn't have to press search after clearing the input box
