### ISSUE TITLE
Add Tooltip in the Community Partner and Sponsor section

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#369]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/197402897-eabd4de2-4014-477e-8bd1-e1e0acee0e60.png)

**Comment by durgeshm01722** [comment]
Hey can you assign me this task?

**Comment by Debajyoti14** [comment]
@durgeshm01722 assigned you

**Comment by durgeshm01722** [comment]
Thanks 🙌

**Comment by durgeshm01722** [comment]
Issue solved in PR no. - #373
