### ISSUE TITLE
Leaderboard search button set disable with no text and change colour when active

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#370]
### Description

The leaderboard search button set is disabled with no text and changes color when active. Set the blue color when the search button is active and set it to gray when disabled.

### Screenshots

![image](https://user-images.githubusercontent.com/91759192/197402981-dd33c9d8-bac5-4a42-89ea-ea5ceadbe0df.png)

**Comment by sudhinm** [comment]
Can I work on this?

**Comment by Debajyoti14** [comment]
@sudhinm assigned you

**Comment by sudhinm** [comment]
@Debajyoti14 This is really unprofessional! If you allow code changes from anyone, please do not assign issues to people and waste their time.

**Comment by Debajyoti14** [comment]
@sudhinm Really sorry bro. Sometime this mistakes happen as we also have review this much of PRs. I will try to be careful from next time. Hope you understand
