### ISSUE TITLE
Fix mobile view for Navbar

### ISSUE THREAD

**Issue by itsmeAnubhab** [Clueless-Community/clueless-official-website#383]
### Description

The login button is not required in the mobile view as there is already login option present in the hamburger. Also the toggle  theme button is overlapping with clueless logo.

### Screenshots

![WhatsApp Image 2022-10-24 at 6 24 08 PM](https://user-images.githubusercontent.com/91974827/197530769-9746770f-0e29-4e03-89e3-9e2378c3eff4.jpeg)

### Additional information

I would like to work on it.

**Comment by Debajyoti14** [comment]
@itsmeAnubhab Assigned you

**Comment by Debajyoti14** [comment]
@itsmeAnubhab Closing this issue for now
