### ISSUE TITLE
Make the "Dive into the world of Development" icons clickable

### ISSUE THREAD

**Issue by TannisthaBiswas** [Clueless-Community/clueless-official-website#385]
Add clickable links to the "Dive into the world of Development" images taking them to documentations or main websites of them. Please assign me with the hacktoberfest tag if you like the idea.
![image](https://user-images.githubusercontent.com/97463197/197589137-07823442-7e67-4fb0-abed-d30b3440e3f8.png)

**Comment by Debajyoti14** [comment]
@TannisthaBiswas assigned you

**Comment by TannisthaBiswas** [comment]
> @TannisthaBiswas assigned you

On it!

**Comment by bhavyasingh75** [comment]
On it.

**Comment by Debajyoti14** [comment]
@TannisthaBiswas Any Update?

**Comment by bhavyasingh75** [comment]
slight glitch at my end.
sending the pr in a few moment.

**Comment by TannisthaBiswas** [comment]
> @TannisthaBiswas Any Update?

Working on it. will probably be done by the end of the day 👍

**Comment by durgeshm01722** [comment]
Can I work on this feature? Please assign me this task.

**Comment by Debajyoti14** [comment]
@durgeshm01722 assigned you

**Comment by durgeshm01722** [comment]
Thanks 🙌

**Comment by durgeshm01722** [comment]
Issue solved in PR no. - #431
