### ISSUE TITLE
Go to github profile on click in leaderboard

### ISSUE THREAD

**Issue by saimaheshtaduri** [Clueless-Community/clueless-official-website#387]
## **Is your feature request related to a problem? Please describe.**
Now on clicking on any user in leaderboard, it's taking nowhere

## **Describe the solution you'd like**
I feel it's better if it redirects to corresponding GitHub profile.

**Comment by saimaheshtaduri** [comment]
@Debajyoti14

**Comment by Rajdip019** [comment]
Go ahead @saimaheshtaduri
