### ISSUE TITLE
Remove search button and show results on typing in searchbox

### ISSUE THREAD

**Issue by saimaheshtaduri** [Clueless-Community/clueless-official-website#388]
## **Is your feature request related to a problem? Please describe.**
Now the user has to click on search, to get results

## **Describe the solution you'd like**
Instead show the results on typing in searchbox.

*

---

*

**Comment by saimaheshtaduri** [comment]
@Debajyoti14

**Comment by Debajyoti14** [comment]
@saimaheshtaduri Go ahead

**Comment by Pawar999** [comment]
Amazing
