### ISSUE TITLE
Add specific details to Figma Community Navbar

### ISSUE THREAD

**Issue by bhavyasingh75** [Clueless-Community/clueless-official-website#389]
![Screenshot (68)](https://user-images.githubusercontent.com/102183018/197845064-c6a924a2-eae3-4f97-9305-d115a3d303a6.png)

I was going through the resources when I came across Figma resources and a navbar displaying "official website".
Where should the "official website" should be redirecting? Could you please clarify?
 I thought that it would redirect me to Figma's official website but it  headed back to home page. 
My suggestion is if you could change the label to "Previous" or "Back to Main" because it looks a bit confusing.

## **Is your feature request related to a problem? Please describe.**

*

---

## **Describe the solution you'd like**

![Screenshot (69)](https://user-images.githubusercontent.com/102183018/197847229-31dafb61-4e25-419c-a9c9-c01280bfc2d0.png)
)

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

*

**Comment by Debajyoti14** [comment]
@bhavyasingh75 Thanks for your concern but this resources page is built with notion which is a No-code tool. So, We can't do much with it. So, Closing this issue.
