### ISSUE TITLE
Fix Profile Project Card for Admin

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#393]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/197962575-82edd715-14f2-4e8a-a8a7-c206882c3394.png)

**Comment by Debajyoti14** [comment]
Use this layout for fixing it which is in visitor view of the profile

![image](https://user-images.githubusercontent.com/91759192/197968438-a806bd68-cebd-46df-aa37-25e8a3e8ed0e.png)

**Comment by RajKanani1206** [comment]
I will like to work on it. Please assign it to me.

**Comment by Debajyoti14** [comment]
@RajKanani1206 assigned you

**Comment by kheersagar** [comment]
hey, if this issue is still pending I can work on it?

**Comment by RajKanani1206** [comment]
Nope, I'm working on it and will be done by today.
