### ISSUE TITLE
Center align the college name in Profile Page 

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#395]
### Description

Align the text center so that the college name looks good.

### Screenshots

![image](https://user-images.githubusercontent.com/91759192/197964864-23556646-1f22-47d7-81c3-c00004d7564c.png)

**Comment by kheersagar** [comment]
hey, can I contribute to this? can you assign me this bug?

**Comment by Debajyoti14** [comment]
@kheersagar assigned you

**Comment by kheersagar** [comment]
Unable to recreate the issue 
# Image
<img width="301" alt="image" src="https://user-images.githubusercontent.com/73149618/198055248-67b0ee63-0e01-41e9-859f-8b9327e76344.png">

**Comment by Debajyoti14** [comment]
@kheersagar I think it's happening due to screen size. You should see if it's breaking in smaller screens as it exists in my screen

**Comment by kheersagar** [comment]
ok
