### ISSUE TITLE
Add hover effect on the profile social icons

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#396]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/197965211-d24fedad-ed46-4b89-8202-db80c70d84cc.png)

**Comment by kheersagar** [comment]
hey,
I am a newbie in open source, I came across this issue and I can contribute to this project by Fixing this bug, can you assign me this bug?

**Comment by Debajyoti14** [comment]
@kheersagar Go for it

**Comment by Debajyoti14** [comment]
after @kheersagar will assign you @Mayureshkaulwar
