### ISSUE TITLE
Fix the Tech stack colour in dark theme in Profile Page

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#397]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/197965581-c4fbe632-51b7-4092-955d-f5ec28d4eb9f.png)

**Comment by RajKanani1206** [comment]
I will like to work on it. Please assign it to me.

**Comment by Debajyoti14** [comment]
@RajKanani1206 assigned you

**Comment by Blazeleo** [comment]
Hi I would liek to work on this as well, can I?
