### ISSUE TITLE
Avatar Initial alignment issue

### ISSUE THREAD

**Issue by kheersagar** [Clueless-Community/clueless-official-website#407]
### Description

If the avatar is a letter than there is an alignment issue, It should be aligned center. 

### Screenshots

<img width="850" alt="image" src="https://user-images.githubusercontent.com/73149618/198078063-0f841267-cd70-4271-9eaf-2b1562bddb33.png">

**Comment by kheersagar** [comment]
Can I fix this?

**Comment by Debajyoti14** [comment]
@kheersagar Go for it
