### ISSUE TITLE
Change this left Image for Rewards and Perks

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#412]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/198176980-8006a01c-313d-4f08-bb1b-f3d61089ed41.png)

**Comment by najeebkp** [comment]
please assign this to me @Debajyoti14

**Comment by Debajyoti14** [comment]
@najeebkp assigned you

**Comment by gaut2003** [comment]
Please assign this to me. @Debajyoti14
