### ISSUE TITLE
Fix the bg for Add Project in Admin Profile Dark Theme

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#413]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/198177234-f085c950-db10-4d24-9806-f1e1f5810cc2.png)

**Comment by SarveshPatil29** [comment]
Hey @Debajyoti14, I would like to work on this issue

**Comment by Debajyoti14** [comment]
@SarveshPatil29 assigned you
