### ISSUE TITLE
Fix Icon colours in Profile Project Card

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#414]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/198177715-c91c22c4-93b5-46df-8b28-24a5eecc7e86.png)

**Comment by sumateja** [comment]
Please assign this to me

**Comment by Debajyoti14** [comment]
@sumateja assigned you

**Comment by sumateja** [comment]
Am waiting for credentials to run this project , can you help me i have already sent email

**Comment by Debajyoti14** [comment]
@sumateja Sent it to you

**Comment by sumateja** [comment]
How can i login as admin what is the url ?

**Comment by Debajyoti14** [comment]
@sumateja Check your profile it will automatically be in admin mode

**Comment by sumateja** [comment]
Profile how , when i click on login all i see is Google & github @Debajyoti14

**Comment by Debajyoti14** [comment]
@sumateja first login into your Google account, then you will see your profile which is admin view itself
