### ISSUE TITLE
Add space between Title and Project Cards

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#416]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/198178931-a01365a6-89df-4933-9d21-beb468b01c3a.png)

**Comment by kheersagar** [comment]
please assign me this

**Comment by SarveshPatil29** [comment]
Hey @Debajyoti14 I am interested in this. Can you please assign me this?

**Comment by Debajyoti14** [comment]
@kheersagar assigned you

**Comment by kheersagar** [comment]
Unable to recreate the issue, tried on a bigger and smaller screen as well.
<img width="238" alt="image" src="https://user-images.githubusercontent.com/73149618/198263136-5659964b-283b-48e3-a2aa-a7739e43718a.png">

**Comment by Debajyoti14** [comment]
ok @kheersagar unassigning you then and assigning @SarveshPatil29. If he doesn't also get this issue, then will close it

**Comment by SarveshPatil29** [comment]
@Debajyoti14 same for me as well. You may close this issue now.

**Comment by encodeArnab** [comment]
Hi @Debajyoti14, I can try to fix this bug, please assign it to me.
Thank You

**Comment by Debajyoti14** [comment]
@encodeArnab are you able to reproduce this issue? Then I will close this issue

**Comment by Debajyoti14** [comment]
@encodeArnab Closing this issue
