### ISSUE TITLE
Add hover effect to name and image of person on leaderboard

### ISSUE THREAD

**Issue by SarveshPatil29** [Clueless-Community/clueless-official-website#418]
## **Is your feature request related to a problem? Please describe.**

* Currently there is no effect when you hover over the username or image of a person in the leaderboard

---

## **Describe the solution you'd like**

* I would like to add these changes

---

**Comment by Debajyoti14** [comment]
@SarveshPatil29 assigned you

**Comment by SarveshPatil29** [comment]
@Debajyoti14 please add hacktoberfest labels as well
