### ISSUE TITLE
[FEATURE] styling contact us section 

### ISSUE THREAD

**Issue by Vanshiii203** [Clueless-Community/clueless-official-website#430]
### Description

I would like to style the contact us section

**Comment by Rajdip019** [comment]
Can you show what you are thinking about the contact us section? @Vanshiii203

**Comment by Vanshiii203** [comment]
> Can you show what you are thinking about the contact us section? @Vanshiii203
Hey @Rajdip019 
I would like to  add the form in a vertical card having glass effect and would like add a background to that page. 
I've Attached an image for your reference.

![Screenshot (510)](https://user-images.githubusercontent.com/94471189/198586089-58af2d63-1a08-4eb5-87b7-1607d74fb958.png)

**Comment by Debajyoti14** [comment]
@Vanshiii203 There image u referenced doesn't go with the theme of our website. Anything else?

**Comment by Vanshiii203** [comment]
> @Vanshiii203 There image u referenced doesn't go with the theme of our website. Anything else?

I have just referenced it for the card and glass effect. I'll add a light theme background as the website has a light theme

**Comment by Debajyoti14** [comment]
@Vanshiii203 But in our entire website Glassmorphism isn't used anywhere. So, it will be weird to just add it for the sake of Contact us page.

**Comment by Vanshiii203** [comment]
What do you think about this one?
![Screenshot (511)](https://user-images.githubusercontent.com/94471189/198677282-8c8ca4e8-ce93-475c-b7a9-f3dcc2b76a69.png)

**Comment by Debajyoti14** [comment]
@Vanshiii203 our's contact us layout is almost same.For now, The contact us layout is good. So, closing this issue
