### ISSUE TITLE
Navbar Alignment Fix

### ISSUE THREAD

**Issue by RajKanani1206** [Clueless-Community/clueless-official-website#432]
### Description

Navbar options alignment is not proper. I guess a recent PR to fix position of dark/light mode button made this issue.

### Screenshots

![image](https://user-images.githubusercontent.com/104709529/198641556-79496c54-2bdd-4d5c-ac45-80e9469a6f88.png)

**Comment by RajKanani1206** [comment]
I would like to work on it. Please assign it to me.

**Comment by Debajyoti14** [comment]
@RajKanani1206 assigned you
