### ISSUE TITLE
Search Bar not closing

### ISSUE THREAD

**Issue by sidling1** [Clueless-Community/clueless-official-website#443]
### Description

On the resources tab , when the search bar is opened , it does not close on clicking the cross icon.

### Screenshots

https://user-images.githubusercontent.com/92554460/205429748-aa68f065-0a78-4356-a6ea-fc9b55775e22.mp4

**Comment by Debajyoti14** [comment]
@sidling1 this page is made with the notion it is a no-code solution, So, cant do anything with it and closing this issue.
