### ISSUE TITLE
Navbar responsive issue

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#444]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/205448728-415334d9-020f-446d-842e-1267f8beba14.png)

**Comment by melencholicmice** [comment]
Hello , i would like to work on this issue can you please assign it to me

**Comment by Debajyoti14** [comment]
@melencholicmice assigning you

**Comment by sankooru14** [comment]
@Debajyoti14 Please assign this issue to me

**Comment by Debajyoti14** [comment]
@sankooru14 after @melencholicmice will assign you.

@melencholicmice also fix the toggle theme button position as it is too close to the Profile avatar

**Comment by Abhijeet-2003** [comment]
@Debajyoti14 Can I work on this issue ?

**Comment by Debajyoti14** [comment]
@melencholicmice Any progress?
