### ISSUE TITLE
Center Align the Header in What is Clueless Section

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#445]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/205448863-0ca65733-e008-4607-8f5d-eea5ccf4186c.png)

**Comment by Akshat2403** [comment]
I want to work on this issue.Please assign it to me

**Comment by Debajyoti14** [comment]
@Akshat2403 assigned yoy

**Comment by sankooru14** [comment]
@Debajyoti14 can you assign this to me?
