### ISSUE TITLE
Fix this Images in for smaller Screens

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#446]
## In Smaller Screen
![image](https://user-images.githubusercontent.com/91759192/205450030-c7bf9303-8288-4212-9c29-e3f6bbe748cd.png)

## In Bigger Screen
![image](https://user-images.githubusercontent.com/91759192/205449997-cab2b994-6487-41dd-b7ae-da7e45aab2bb.png)

**Comment by shivamgupta2020** [comment]
I want to work on this. Please assign me.

**Comment by Debajyoti14** [comment]
@shivamgupta2020 assigned you
