### ISSUE TITLE
Design this Codepeak Section

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#447]
### Design this section properly so that it looks good for smaller screens.
Don't forget to share your design before developing it.

### Screenshots

![image](https://user-images.githubusercontent.com/91759192/205450235-ea429ff4-2fcf-4dd7-94f1-0d1e7f324041.png)

**Comment by Debajyoti14** [comment]
@Tushar98644 Go for it

**Comment by StrixROX** [comment]
Came up with this design. Should I work on it?

[ Light Mode ]
Desktop:
![image](https://user-images.githubusercontent.com/40167899/209018967-16134548-c01b-4429-86a3-1f61cbdbe9a6.png)

Tab:
![image](https://user-images.githubusercontent.com/40167899/209019033-930b6de6-0a6f-4bce-b6f6-32e8634bb8cf.png)

Mobile:
![image](https://user-images.githubusercontent.com/40167899/209019063-a235f416-7cf8-4403-b2f8-4bdc14631cad.png)

[ Dark Mode ]
Desktop:
![image](https://user-images.githubusercontent.com/40167899/209019128-3c644443-727f-4ce4-bc35-f885665e27e1.png)

Tab:
![image](https://user-images.githubusercontent.com/40167899/209019146-cd5e2409-3b19-42b8-b3d8-e244416d80f1.png)

Mobile:
![image](https://user-images.githubusercontent.com/40167899/209019164-965c8cbf-3edd-4bee-a035-a9e5ba601343.png)

**Comment by money8203** [comment]
Looks great @StrixROX!

**Comment by Debajyoti14** [comment]
@StrixROX looks good just left align the text for bigger screen & make the headline text less bolder
It's good to go.
Assigning to you then.

**Comment by StrixROX** [comment]
Which screen size are you referring to @Debajyoti14 ?

**Comment by Debajyoti14** [comment]
@StrixROX For the Desktop & Tab screens in both Light & Dark Theme

**Comment by StrixROX** [comment]
@Debajyoti14 please review my PR
