### ISSUE TITLE
Multiple Tech Stack in Profile Edit Section

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#449]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/205496313-70040e8f-c674-4cf5-b9ee-8729b5f7dc1b.png)

**Comment by harsh-na** [comment]
okay sir I want to fix this issue

**Comment by Debajyoti14** [comment]
@harsh-na assigned you

**Comment by Sparsh752** [comment]
can I work on this

**Comment by Sparsh752** [comment]
@Debajyoti14 Can I work on this

**Comment by ankushj0801** [comment]
Can I work on this if it is open?

**Comment by harsh-na** [comment]
@Debajyoti14 I had completed this issue 
and surely create a PR after completing one more issue which is related to this issue somewhat...
