### ISSUE TITLE
Dropdown Colour Change in Profile Edit Section for Dark Mode

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#450]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/205496388-209976be-d420-4ce8-90d2-d41c46c74667.png)

**Comment by harsh-na** [comment]
sir where I could find the tech stack section in website

**Comment by Debajyoti14** [comment]
@harsh-na just go to your profile and click on the edit profile button.
You can see the techstack field where you will see all the Techstack listed.

In the codebase, The Techstacks are mentioned inside database folder
database/techstack -> Path

**Comment by harsh-na** [comment]
okay sir I want to work on this issue

**Comment by Debajyoti14** [comment]
@harsh-na Go for it

**Comment by Sparsh752** [comment]
@Debajyoti14 Can I work on this

**Comment by Debajyoti14** [comment]
@Sparsh752 Wait for @harsh-na to finish

**Comment by ankushj0801** [comment]
Can I work on this if it is open? @Debajyoti14

**Comment by harsh-na** [comment]
@ankushj0801 have you fixed this issue...
