### ISSUE TITLE
In Dark Mode Mobile menu section should be Dark (black)

### ISSUE THREAD

**Issue by AbhiPatel10** [Clueless-Community/clueless-official-website#454]
### Description

When we open the mobile menu section in light mode, it is white; however, when we open it in dark mode, it also has a white background; therefore, in dark mode, the menu section should be dark and the text should be white. 

@Debajyoti14 please assign me this issue...

### Screenshots

![Screenshot 2022-12-05 123718](https://user-images.githubusercontent.com/76242769/205574576-964a38ee-1176-4381-9b40-e5c802a018a3.jpg)

**Comment by Debajyoti14** [comment]
@AbhiPatel10 Go for it and also make sure to change the text colours accordingly

**Comment by AbhiPatel10** [comment]
Sure and please also add codepeak22 label on it.

**Comment by AbhiPatel10** [comment]
My laptop is not supporting, it's take much more time to run the code so someone please take this issue.

**Comment by Debajyoti14** [comment]
@AbhiPatel10 Okay

**Comment by Yogeshlodhi** [comment]
Doesn't your website contain the html file?

**Comment by Debajyoti14** [comment]
@Yogeshlodhi This website is made with NextJS which is a framework of React

You will not see any html
Everything is written in JSX

**Comment by ankushj0801** [comment]
can I work on this issue if it is open?

**Comment by dheerajchhatanidc** [comment]
Please assign me this if this issue is open @Debajyoti14

**Comment by Debajyoti14** [comment]
@dheerajchhatanidc assigning you

**Comment by dheerajchhatanidc** [comment]
Please add SWOC tag as I want to contribute under SWOC 3.0

**Comment by Sathvik902** [comment]
Can I work on this @Debajyoti14?

**Comment by Debajyoti14** [comment]
@Sathvik902 Yup assigning you
