### ISSUE TITLE
Change Favicon Icon

### ISSUE THREAD

**Issue by AbhiPatel10** [Clueless-Community/clueless-official-website#455]
### Description

Favicon Icon with white background is not looks good please remove white background and add a new Fav icon...

@Debajyoti14 Please Assign this task to me and add a label codepeak22

### Screenshots

![Screenshot 2022-12-05 125725](https://user-images.githubusercontent.com/76242769/205578179-6420859b-158d-464e-a8a3-3f834418b1d1.jpg)

**Comment by Debajyoti14** [comment]
@AbhiPatel10 assigned you
