### ISSUE TITLE
Navbar UI Enhancement

### ISSUE THREAD

**Issue by Yogeshlodhi** [Clueless-Community/clueless-official-website#459]
### Description

Styling of the elements in the navbar can be made better and some hover effects can also be added all over the website to make it look live.

**Comment by Yogeshlodhi** [comment]
@Debajyoti14 
Kindly assign this issue to me and add label ass Codepeak

**Comment by Yogeshlodhi** [comment]
The highlighted border may be removed to give it a sober look and the
coloring of the icons on hovering and off hovering may be altered to give
it some realistic look

**Comment by Yogeshlodhi** [comment]
Great, thanks!

**Comment by Yogeshlodhi** [comment]
@Debajyoti14 Kindly award the points for raising the issue if you find it sensible.

**Comment by Yogeshlodhi** [comment]
Sorry I can't work on this issue as i'm not familiar with TS and Next.js

**Comment by Debajyoti14** [comment]
@Yogeshlodhi Okay no worries. Closing this issue for now
