### ISSUE TITLE
Add animation in the Home Page

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#468]
### Additional information

![image](https://user-images.githubusercontent.com/91759192/208767159-c1c4ad08-e203-45d8-b96b-bc8cf371fd2d.png)

**Comment by sidling1** [comment]
Can I solve this

**Comment by Alok-1512** [comment]
Can you elaborate a bit like the direction or something or how you want things to be animated

**Comment by money8203** [comment]
You can add animation effects, transition effects and make the website more responsive

**Comment by Debajyoti14** [comment]
@sidling1 do you want to work on it?

**Comment by Debajyoti14** [comment]
@Sathvik902 assigning it to you

**Comment by Sathvik902** [comment]
Actually I am having problem while running this website in localhost..
Can you guide me?? @Debajyoti14

**Comment by Debajyoti14** [comment]
@Sathvik902 Sure
Do you have the .env file??

**Comment by Sathvik902** [comment]
@Debajyoti14  `next-env.d.ts` file is there

**Comment by Sathvik902** [comment]
what are the additional dependencies which I need to install inorder to run in localhost?

**Comment by Sathvik902** [comment]
This is the error I am getting when I `npm run dev`

![Screenshot (242)](https://user-images.githubusercontent.com/92165565/212333742-e519fee4-046c-4661-9eff-1d90d4d1cbd4.png)

**Comment by Debajyoti14** [comment]
@Sathvik902 Mail us at official.cluelesscommunity@gmail.com for the env file content
Then make a .env.local file in root of your project and add the copy paste the content
Then you can run the project

**Comment by Sathvik902** [comment]
Okay, I figured it out!
Site is running in localhost.
Thank you @Debajyoti14

**Comment by Debajyoti14** [comment]
@Sathvik902 Nice

**Comment by Sathvik902** [comment]
Done with the work @Debajyoti14 ..
Added the transition animation to the landing page of the website

**Comment by Sathvik902** [comment]
Please accept my PR

**Comment by Debajyoti14** [comment]
@Sathvik902 No PR is there. Check once again and make a PR

**Comment by Sathvik902** [comment]
Created!

**Comment by Sathvik902** [comment]
@Debajyoti14

**Comment by Sathvik902** [comment]
Created @Debajyoti14

**Comment by Sathvik902** [comment]
Made a PR @Debajyoti14

**Comment by Debajyoti14** [comment]
@Sathvik902 Sorry but there aren't any open PR's

**Comment by Sathvik902** [comment]
How about now? @Debajyoti14

**Comment by Debajyoti14** [comment]
@Sathvik902 merged it

**Comment by Sathvik902** [comment]
Okay!

**Comment by Sathvik902** [comment]
Anything else to be added @Debajyoti14 ??

if you describe the type of animation, I'll try to add the same.

**Comment by khushigarg1** [comment]
Please assign it to me I no completed!

**Comment by Debajyoti14** [comment]
@khushigarg1 It's done only for the Hero section at home screen

You can add it to other screens

**Comment by khushigarg1** [comment]
> @khushigarg1 It's done only for the Hero section at home screen
> 
> You can add it to other screens

Okay thank you i will.

**Comment by charu1603** [comment]
I want to work on this issue @Debajyoti14 . Please assign it to me
