### ISSUE TITLE
[UX FIX] Add Dark mode toggle button instead of a Dropdown

### ISSUE THREAD

**Issue by MAX-786** [Clueless-Community/clueless-official-website#469]
### Description

When I click on Dark mode button it opens up a dropdown menu. I have to click 2 times to switch my theme. Since there are only Dark/Light themes a single toggle button would be good UX improvement. Thanks! Feedback welcome.

### Screenshots

![Screenshot_20221230_191932](https://user-images.githubusercontent.com/99530996/210077662-2c99ee37-9c8d-4357-8e32-299f4221d708.png)

![Screenshot_20221230_192009](https://user-images.githubusercontent.com/99530996/210077628-bd74cce4-1444-4292-8dd5-f79164e03159.png)

**Comment by daredevil3435** [comment]
can I try working on this?

**Comment by MAX-786** [comment]
Yeah! sure

**Comment by MaYaNkKashyap681** [comment]
Please assign this to me.

**Comment by Debajyoti14** [comment]
@daredevil3435 assigning it to you.

**Comment by daredevil3435** [comment]
@Debajyoti14 unassign me.

**Comment by AaryaaRam** [comment]
@Debajyoti14 I would like to work on this one!!

**Comment by Debajyoti14** [comment]
@AaryaaRam assigning you

**Comment by Tushar98644** [comment]
If this issue still persists,pls assign me @Debajyoti14

**Comment by Savio629** [comment]
### Hey @Debajyoti14 I would like to work on this issue.
### So you just want to remove the dropdown menu and change the theme when clicked :
<img src="https://user-images.githubusercontent.com/91362589/210801553-52f02e02-a7b8-43fd-8c3f-e5ea08f0b256.png" width="600">


### or add a toggle button to change the theme when the toggle button is clicked: 
<img src="https://user-images.githubusercontent.com/91362589/210800638-2adaf9fb-a236-46cc-a430-9b93fce0ae58.png" width="600">

**Comment by Debajyoti14** [comment]
@Savio629 you can add a toggle button which toggles the theme basically

**Comment by Savio629** [comment]
Is it fine if I use npm package for this issue ? @Debajyoti14

**Comment by lokeshvasnik** [comment]
looks interesting

**Comment by Debajyoti14** [comment]
@Savio629 Yup, you can do that

**Comment by Savio629** [comment]
Will start working on it immediately..

**Comment by Debajyoti14** [comment]
@Savio629 any update?

**Comment by khushigarg1** [comment]
Please assign this issue to me, If not completed!

**Comment by Debajyoti14** [comment]
@khushigarg1 assigning you too
