### ISSUE TITLE
[ADD FEATURE] Add a discussion forum 

### ISSUE THREAD

**Issue by MAX-786** [Clueless-Community/clueless-official-website#471]
## **Is your feature request related to a problem? Please describe.**

Every resource section like this [React resource section](https://clueless-resources.super.site/resources/tech/web-development/react) deserves thier own discussion/comment section at bottom. I have reasons to support this like
- it will make you closer w/ your audience
- people then can discuss which resources are very helpful, what resources are UPDATED/OUTDATED ,and help others share thier example which can help others.

For this clueless have to introduce a Login system or any other solution so it can remain out of spamming. Thanks!
Feedback Welcome.

**Comment by Sathvik902** [comment]
I would like to work on this. kindly assign me @MAX-786

**Comment by MAX-786** [comment]
@Sathvik902 I would love to but in this repo only maintainers can assign issue.

cc: @Debajyoti14 @Rajdip019 can you guys please look into this and if this feature interests you, it's a bit big for single issue so it should be divided in tasks. Thanks!

**Comment by Debajyoti14** [comment]
@MAX-786 The resource section is made with a no-code tool called notion.
You can not change the layout of it.

**Comment by Debajyoti14** [comment]
@MAX-786 It's not necessary right now to update it. Maybe we can think of it when we migrate it to no-code to code. For now closing this issue.
