### ISSUE TITLE
[DOCS] Add Issues Heading in CONTRIBUTING.md

### ISSUE THREAD

**Issue by clairecharles** [Clueless-Community/clueless-official-website#473]
### Description

In CONTRIBUTING.md, contributors need to know the right way to add an issue. For example, if a contributor needs to report a bug then they should see the right way to report it in the CONTRIBUTING.md.

### Screenshots

The issues heading section should look like this
![Screenshot 2023-01-04 at 12 24 05](https://user-images.githubusercontent.com/67120042/210545071-5212b0be-77e7-4394-8109-8f209a008bd7.png)

The change shouldn't look exactly like this :)

**Comment by Debajyoti14** [comment]
@clairecharles Go for it
