### ISSUE TITLE
Ui/ UX design upto next level and smooth workflow

### ISSUE THREAD

**Issue by PRABHU-OFFICIAL** [Clueless-Community/clueless-official-website#479]
## **Is your feature request related to a problem? Please describe.**

* I know the UI is simple but now a days after the development of next gen websites the wenbsites should be developed in such a way that it should step out of every other tech

---

## **Describe the solution you'd like**

* We can redesign the websites Ui by using next jen technologies like tailwind css and media screen improvements for smooth display rendering. 

---

## **Describe alternatives you've considered**

* Just some enhancements for the UI in some areas in simple frames

**Comment by Debajyoti14** [comment]
Closing this issue as we will be updating the UI very soon and open issues regarding that. sit tight.
