### ISSUE TITLE
Ideas for Winter of Code ( WOC ) 2023

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#489]
### What would you like to share?

1. We will update our whole Clueless Website UI to make it more modern and engaging. `NextJS`, `React`, `TailwindCSS` knowledge is necessary. Knowledge of `Firebase` and Animation will be a plus.

2. We will add some new features like profile search, custom profile URL, and stuff like that where `Firebase` will be required.

You can make proposals for the following ideas.

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me
