### ISSUE TITLE
Hero Section Revamped UI

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#493]
### Build the Hero Section
![image](https://user-images.githubusercontent.com/91759192/218295364-7ee51be7-16e8-44be-908b-3454368108da.png)

Design the responsive UI as it is there in the Figma file

### Additional information

Have a look at the Figma Design 
https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=2330%3A7211&t=u23pNyuQlhrFByO2-1

The globe on the right side can be implemented by using this package
https://www.npmjs.com/package/cobe

**Comment by arun-kushwaha04** [comment]
@Debajyoti14 can I work on this issue ?

**Comment by Naveen-7000** [comment]
Hello @Debajyoti14 ,
I have worked on similar issue previously . I have experience with this kind of problem , could you please assign me this issue ?

**Comment by Debajyoti14** [comment]
@Naveen-7000 assigning you

**Comment by Debajyoti14** [comment]
@Naveen-7000 Whats's the update?

**Comment by Naveen-7000** [comment]
@Debajyoti14 sorry for delay, i am steel figuring out few things could you please assign to someone else the issue

**Comment by Debajyoti14** [comment]
@Naveen-7000 okay

**Comment by jsuryakt** [comment]
@Debajyoti14 I will try to work on this issue

**Comment by Debajyoti14** [comment]
@jsuryakt assigned you

**Comment by bbsdevloper** [comment]
@jsuryakt Are you currently working on this issue?

**Comment by sarkartanmay393** [comment]
@bbsdevloper I would like to take it under JWOC, and do I need to build the navbar also ?

**Comment by bbsdevloper** [comment]
@sarkartanmay393 no need to build the Navbar?

**Comment by bbsdevloper** [comment]
@sarkartanmay393 🚀

**Comment by sarkartanmay393** [comment]
> @sarkartanmay393 no need to build the Navbar?

Whatever, I'll start working on it.
