### ISSUE TITLE
Testimonial Section Revamped UI 

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#495]
### Revamped Testimonial Section?
![image](https://user-images.githubusercontent.com/91759192/218295694-d0aba0b4-1d3e-4fdf-a8a2-393d1111b593.png)

Develop a responsive UI for the Testimonial section in the Revamped Design

### Additional information

Refer to the Figma Design
https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=2330%3A7211&t=u23pNyuQlhrFByO2-1

**Comment by arun-kushwaha04** [comment]
@Debajyoti14 can I take this issue ??

**Comment by Debajyoti14** [comment]
@arun-kushwaha04 assigning you
Please mention if you are contributing under any Open-source event like WOC or JWOC

**Comment by arun-kushwaha04** [comment]
Nope not contributing under WOC or JWOC

**Comment by Debajyoti14** [comment]
@arun-kushwaha04 no worries

**Comment by Debajyoti14** [comment]
@arun-kushwaha04 Any Update?

**Comment by arun-kushwaha04** [comment]
Working on it

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by bbsdevloper** [comment]
@arun-kushwaha04 Are you currently working on this issue?

**Comment by bbsdevloper** [comment]
@neokd Want to work ?

**Comment by neokd** [comment]
Ya sure

**Comment by bbsdevloper** [comment]
@neokd  Go ahead :)

**Comment by neokd** [comment]
Thanks

**Comment by neokd** [comment]
Thanks , I'm working on this under JWOC
