### ISSUE TITLE
Sponsors revamped UI Design

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#496]
### Revamped Sponsor Section
![image](https://user-images.githubusercontent.com/91759192/218295616-1a090623-fc26-4008-a6ed-aa41328611e1.png)

Develop a responsive UI for Sponsor section in the Revamped UI Design

### Additional information

Refer to the Figma Design
https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=2330%3A7211&t=u23pNyuQlhrFByO2-1

**Comment by Mysterious786** [comment]
Assign me this.

**Comment by Debajyoti14** [comment]
@Mysterious786 What's the Update?

**Comment by bbsdevloper** [comment]
@Mysterious786 Are you currently working on this issue?

**Comment by bbsdevloper** [comment]
@Mysterious786 Okay.
Try to do it ASAP.

**Comment by Mysterious786** [comment]
ok
