### ISSUE TITLE
Revamp Footer Design

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#497]
### Revamp Footer Design
![image](https://user-images.githubusercontent.com/91759192/218295473-2d83e2e9-41c7-42ff-9151-77ec38d9887e.png)

Develop a responsive UI for the Footer section in the Revamped UI Design

### Additional information

Refer to the Figma Design
https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=2330%3A7211&t=u23pNyuQlhrFByO2-1

**Comment by sajdakabir** [comment]
Hey @Debajyoti14 , I would like to work on this issue can you please assige it to me?

**Comment by Debajyoti14** [comment]
@sajdakabir assigning you

**Comment by KrunalGupta02** [comment]
@Debajyoti14 i want to work on this issue

**Comment by Debajyoti14** [comment]
@KrunalGupta02 Are you contributing under jwoc?

**Comment by KrunalGupta02** [comment]
Yes @Debajyoti14

**Comment by Debajyoti14** [comment]
@sajdakabir What's the update?

**Comment by Debajyoti14** [comment]
@KrunalGupta02 will assign you if you are ready?
Are you participating under JWOC?

**Comment by KrunalGupta02** [comment]
Yeah plz assign me i want to work and i am jwoc participant too

**Comment by Debajyoti14** [comment]
@KrunalGupta02 For your ease, You can copy the footer from the main branch itself and tweak the colour and other small changes.

And it will be done

**Comment by KrunalGupta02** [comment]
Can u tell where it is present in the main branch i mean in which folder

**Comment by Debajyoti14** [comment]
@KrunalGupta02 https://github.com/Clueless-Community/clueless-official-website/blob/main/pages/components/shared/Footer.tsx

**Comment by KrunalGupta02** [comment]
Okk thanks 👍🏻

**Comment by Debajyoti14** [comment]
@KrunalGupta02 What's the update?

**Comment by KrunalGupta02** [comment]
> @KrunalGupta02 What's the update?

Sorry i will upload tomorrow 
Currently my exams are running but i will upload tomorrow definitely

**Comment by KrunalGupta02** [comment]
@Debajyoti14 kindly unassign me this issue

**Comment by sarkartanmay393** [comment]
@Debajyoti14 Let me solve this under JWOC.

**Comment by sarkartanmay393** [comment]
Someone close this issue
