### ISSUE TITLE
Adding Unit Test Using Jest 

### ISSUE THREAD

**Issue by Jagroop2000** [Clueless-Community/clueless-official-website#500]
## **🚀 Feature Request**

**Subject:** Request for Jest integration in ReactJS projects on GitHub
**Hi there !!**

I am writing to request the **integration of Jest,** a popular JavaScript testing library, into your project that uses ReactJS. This would allow developers to write and run unit tests for their React components directly on the platform. Jest's simplicity and power would greatly improve the development experience and increase the reliability of code.

And the good thing is Jest testing files wouldn't add any memory consumption to the project when we make a build or it is on production.

Thank you for considering this request. I look forward to your response.

Best regards,
Jagroop

**Comment by bbsdevloper** [comment]
@Jagroop2000 are you doing ?
