### ISSUE TITLE
Build Revamped UI Design of Tutorial Hell Section

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#502]
### What would you like to share?

Build this revamped UI of the following section
![image](https://user-images.githubusercontent.com/91759192/218836055-7ad37529-26e2-457e-836d-f2c0e927c9d3.png)

The left section will be interactive not an image
Refer to this video for the interactive codepad from here
https://www.loom.com/share/d53b431527e440e68157891b50c018cd

### Additional information

Refer to the Figma Design
https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=2330%3A7211&t=u23pNyuQlhrFByO2-1

**Comment by gnaneshwar718** [comment]
I want to contribute to it under jwoc

**Comment by ARYA-RAY** [comment]
assign
