### ISSUE TITLE
Develop Revamped What is Clueless? Design

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#503]
### What would you like to share?

Develop this revamped UI of the following section
![image](https://user-images.githubusercontent.com/91759192/218837140-74f8bfe3-711d-48f2-b5ef-a042fb617d09.png)

### Additional information

Refer to the Figma Design
https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=2330%3A7211&t=u23pNyuQlhrFByO2-1

**Comment by anikdhabal** [comment]
Can I work on this?

**Comment by Debajyoti14** [comment]
@anikdhabal Are you contributing under any open-source event?

**Comment by Debajyoti14** [comment]
ok @anikdhabal assigning you

**Comment by Debajyoti14** [comment]
@anikdhabal What's the Update?

**Comment by anikdhabal** [comment]
@Debajyoti14  I will complete it by today.

**Comment by Debajyoti14** [comment]
@anikdhabal What's the update?

**Comment by bbsdevloper** [comment]
@anikdhabal any update?

**Comment by sarkartanmay393** [comment]
@Debajyoti14 Assign me after #519 under JWOC

**Comment by bbsdevloper** [comment]
@sarkartanmay393 go ahead .....:)

**Comment by sarkartanmay393** [comment]
> @sarkartanmay393 go ahead .....:)

i  raised pr of it

**Comment by sarkartanmay393** [comment]
@bbsdevloper Take look at my PR
