### ISSUE TITLE
Develop this Revamped Open-Source Profile UI

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#505]
### What would you like to share?

Develop this **Open-Source Profile UI**

![image](https://user-images.githubusercontent.com/91759192/218839431-0ff18000-bdba-4de3-b383-12e630fef54b.png)

### Additional information

Refer to the Figma Design
https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=2330%3A7211&t=u23pNyuQlhrFByO2-1

**Comment by gnaneshwar718** [comment]
I want to contribute to it under jwoc

**Comment by Debajyoti14** [comment]
@gnaneshwar718 assigning you

**Comment by Debajyoti14** [comment]
@gnaneshwar718 What's the Update?

**Comment by Zubair-05** [comment]
@Debajyoti14 I want to work on this issue. Can you please assign it to me under JWOC.

**Comment by Priyamakeshwari** [comment]
I would like to work on this issue under JWOC

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by gnaneshwar718** [comment]
Sorry for late reply I just had IA

**Comment by sarkartanmay393** [comment]
#### I would like to take it on, @Debajyoti14.

**Comment by bbsdevloper** [comment]
@Zubair-05 Do you want to work on this issue now ?

**Comment by Zubair-05** [comment]
@bbsdevloper Yes of course. I want to work on this issue.

**Comment by bbsdevloper** [comment]
Go ahead @Zubair-05

**Comment by bbsdevloper** [comment]
@Zubair-05  is it done ❓

**Comment by Zubair-05** [comment]
@bbsdevloper I'm really sorry that I'm not able to finish the task. I request you to assign this issue to somebody else.
