### ISSUE TITLE
Develop this World of Open-Source Section

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#506]
### What would you like to share?

Build this **World of Open-Source** Section

![image](https://user-images.githubusercontent.com/91759192/218840365-eb190e2c-e577-43a3-9a74-99fb8c9d698b.png)

Use this framer-motion animation to implement this but there will be multiple objects as specified in the design
https://codesandbox.io/s/framer-motion-drag-with-constraints-pjn6t

### Additional information

Refer to the Figma Design
https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=2330%3A7211&t=u23pNyuQlhrFByO2-1

**Comment by ayushanand308** [comment]
@Debajyoti14 ,can you assign me this issue under JWOC

**Comment by sarkartanmay393** [comment]
@Debajyoti14 I would love to work on this issue.

**Comment by Debajyoti14** [comment]
@sarkartanmay393 assigning you

**Comment by sarkartanmay393** [comment]
@Debajyoti14 Review my PR

**Comment by sarkartanmay393** [comment]
@Debajyoti14 Can you check it out again?

**Comment by sarkartanmay393** [comment]
@Debajyoti14 you can close this issue by now.
