### ISSUE TITLE
Build Revamped Open-Source Programs Section

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#507]
### What would you like to share?

Build Revamped Open-Source Programs Section
Mention under which Open-Source Program you are contributing

![image](https://user-images.githubusercontent.com/91759192/218845224-ea16eb8c-1d77-49db-ac59-4b1f989a38e5.png)

### Additional information

Refer to the Figma Design
https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=2330%3A7211&t=u23pNyuQlhrFByO2-1

**Comment by CS50X-RGB** [comment]
@Debajyoti14 can i get this issue?

**Comment by Debajyoti14** [comment]
@CS50X-RGB are you working under JWOC?

**Comment by CS50X-RGB** [comment]
> @CS50X-RGB are you working under JWOC?

Yupp

**Comment by Debajyoti14** [comment]
@CS50X-RGB assigned you

**Comment by CS50X-RGB** [comment]
> > @CS50X-RGB are you working under JWOC?
> 
> Yupp

What is the last date for the submission?

**Comment by CS50X-RGB** [comment]
> @CS50X-RGB assigned you
What is the last date of submission?

**Comment by Debajyoti14** [comment]
> > @CS50X-RGB assigned you
> What is the last date of submission? 

Try to do it within max 2-3 days

**Comment by CS50X-RGB** [comment]
Hi @Debajyoti14 i have created the pc version of the website but i am getting problems converting it to mobile

**Comment by CS50X-RGB** [comment]
This is the version i made for pc

**Comment by CS50X-RGB** [comment]
https://codesandbox.io/p/sandbox/vibrant-ptolemy-2cgy7d?selection=%5B%7B%22endColumn%22%3A17%2C%22endLineNumber%22%3A7%2C%22startColumn%22%3A17%2C%22startLineNumber%22%3A7%7D%5D&file=%2Fpages%2FComponents%2FOpenSoruce.jsx and if u could help here is the code

**Comment by Udit-Shukla** [comment]
can u assign me this issue?

**Comment by Debajyoti14** [comment]
@CS50X-RGB What's the progress?

**Comment by CS50X-RGB** [comment]
> @CS50X-RGB What's the progress?

I will do it by tomorrow I had my exam today sorry for the delay 😅
