### ISSUE TITLE
Build Revamped UI of Lacking Skills Section

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/clueless-official-website#508]
### What would you like to share?

Build Revamped UI of Lacking Skills Section

![image](https://user-images.githubusercontent.com/91759192/218845820-5c8cb9dc-117b-4dd1-8711-ea4ea0186dab.png)

### Additional information

Refer to the Figma Design
https://www.figma.com/file/QJdOAP9EB3CbiK3dOiOfaL/ClueLess?node-id=2330%3A7211&t=u23pNyuQlhrFByO2-1

**Comment by amdpt323** [comment]
i want to claim this issue 
just needed a bit information how to develop these dotted lines

**Comment by Debajyoti14** [comment]
@amdpt323 No need to code this dotted line
According to me, export the image from figma as SVG and position it correctly

**Comment by amdpt323** [comment]
can you help me with where is the old UI of lacking skills path in the project dir D'

**Comment by Debajyoti14** [comment]
@amdpt323 There's no old section called lacking skill section.
You have to build it from scratch and push it to dev branch
