### ISSUE TITLE
Official Website in Not Opening.

### ISSUE THREAD

**Issue by anikdhabal** [Clueless-Community/clueless-official-website#510]
### Description

Official Website in Not Opening

### Screenshots
<img width="1080" alt="Screenshot 2023-02-17 210624" src="https://user-images.githubusercontent.com/81948346/219697175-51e4daaf-a11d-481d-8cb9-e68bd8daa2fc.png">

**Comment by Debajyoti14** [comment]
@anikdhabal Actually the domain got expired some days back.
That's why.
it will be fixed once we renew our domain plan
