### ISSUE TITLE
Fix Tutorial hell in Mobile view

### ISSUE THREAD

**Issue by bbsdevloper** [Clueless-Community/clueless-official-website#554]
### Description

Fix it before 3rd April 2023

### Screenshots

![WhatsApp Image 2023-04-03 at 15 34 04](https://user-images.githubusercontent.com/99157367/229479405-54396604-f187-4e76-92f5-bcfd504a722c.jpg)

**Comment by Debajyoti14** [comment]
@bbsdevloper is me kya fix karna hain?

**Comment by bbsdevloper** [comment]
Bhai overflow ho raha ha mobile ma

**Comment by RavindraP04** [comment]
@Debajyoti14 @bbsdevloper Fixed this one in #561
