### ISSUE TITLE
Testimonial Section Issue

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/clueless-official-website#573]
### Testimonial section's space between the card is too much below lg and above sm 
![image](https://user-images.githubusercontent.com/98400348/230719919-f149c2d5-085a-4d08-a53b-e72aa16c5635.png)

**Comment by Akshaykumar4524** [comment]
Hi @RavindraP04 created PR for the same can you please have look into this

**Comment by RavindraP04** [comment]
> Hi @RavindraP04 created PR for the same can you please have look into this

@Debajyoti14 @bbsdevloper Please review the PR
