### ISSUE TITLE
Testimonial fixes

### ISSUE THREAD

**Issue by bbsdevloper** [Clueless-Community/clueless-official-website#578]
![image](https://user-images.githubusercontent.com/99157367/231221189-a0898c15-fe15-4ce5-9f99-4d7a5071ad20.png)

**Comment by Debajyoti14** [comment]
@hritikbhattacharya We are not going with the previous design of Testimonial.
Go through this https://help.twitter.com/en/using-twitter/how-to-embed-a-tweet
and try to embed all the tweets in a carousel for all desktop to big screens
As a reference check,
https://wemakedevs.org/ Testimonial Section
